apiVersion: apps/v1
kind: Deployment
metadata:
  name: stiggsyncai-api
  namespace: stiggsyncai-prod
  labels:
    app: stiggsyncai-api
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stiggsyncai-api
  template:
    metadata:
      labels:
        app: stiggsyncai-api
        version: v1
    spec:
      containers:
      - name: stiggsyncai-api
        image: acrstiggsyncai.azurecr.io/stiggsyncai:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: stiggsyncai-secrets
              key: db-connection-string
        - name: ConnectionStrings__Redis
          valueFrom:
            secretKeyRef:
              name: stiggsyncai-secrets
              key: redis-connection-string
        - name: AzureOpenAI__Endpoint
          valueFrom:
            secretKeyRef:
              name: stiggsyncai-secrets
              key: openai-endpoint
        - name: AzureOpenAI__ApiKey
          valueFrom:
            secretKeyRef:
              name: stiggsyncai-secrets
              key: openai-api-key
        - name: KeyVaultUrl
          valueFrom:
            configMapKeyRef:
              name: stiggsyncai-config
              key: keyvault-url
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: stiggsyncai-secrets
              key: appinsights-connection-string
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
      volumes:
      - name: app-logs
        emptyDir: {}
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stiggsyncai-config
  namespace: stiggsyncai-prod
data:
  keyvault-url: "https://kv-stiggsyncai-prod.vault.azure.net/"
  features-blockchain: "true"
  features-digitaltwins: "true"
  features-esg: "true"
  features-mobile: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: stiggsyncai-secrets
  namespace: stiggsyncai-prod
type: Opaque
data:
  # These values should be base64 encoded and stored securely
  # In production, use Azure Key Vault integration
  db-connection-string: <base64-encoded-connection-string>
  redis-connection-string: <base64-encoded-redis-string>
  openai-endpoint: <base64-encoded-openai-endpoint>
  openai-api-key: <base64-encoded-openai-key>
  appinsights-connection-string: <base64-encoded-appinsights-string>
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stiggsyncai-hpa
  namespace: stiggsyncai-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stiggsyncai-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60