import { FormEvent, useCallback, useEffect, useState } from "react";
import type { OrgMember } from "../../services/developService";
import {
  acknowledgeOperationalDebt,
  getCaseOperationalDebt,
  getOperationalDebtCandidates,
  recordOperationalDebtReference,
  type OperationalDebtCandidate,
  type OperationalDebtItem,
} from "../../services/operationalDebtService";
const label=(v:string)=>v.replaceAll("_"," ");
export function OperationalDebtPanel({caseId,members,canPlan,canAcknowledge}:{caseId:string;members:OrgMember[];canPlan:boolean;canAcknowledge:boolean}){const[items,setItems]=useState<OperationalDebtItem[]>([]);const[candidates,setCandidates]=useState<OperationalDebtCandidate[]>([]);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);const load=useCallback(()=>Promise.all([getCaseOperationalDebt(caseId),getOperationalDebtCandidates(caseId)]).then(([r,c])=>{setItems(r.items);setCandidates(c);}).catch(e=>setError(e instanceof Error?e.message:"Unable to load operational debt")),[caseId]);useEffect(()=>{void load();},[load]);
async function record(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const key=String(f.get("candidate"));const c=candidates.find(x=>`${x.gapClass}|${x.sourceTable}|${x.sourceId}`===key);if(!c)return;setBusy(true);setError(null);try{await recordOperationalDebtReference(caseId,c,String(f.get("owner")),String(f.get("due"))||null);e.currentTarget.reset();await load();}catch(x){setError(x instanceof Error?x.message:"Registration refused");}finally{setBusy(false);}}
async function acknowledge(id:string){const basis=window.prompt("State the operations acknowledgement evidence basis (minimum 20 characters):");if(!basis)return;try{await acknowledgeOperationalDebt(id,basis);await load();}catch(x){setError(x instanceof Error?x.message:"Acknowledgement refused");}}
return <section className="rounded-xl border border-white/6 bg-[#0D1520] p-5"><h2 className="text-sm font-semibold text-white">Operational debt at handover</h2><p className="mt-1 text-xs text-slate-400">Nine gap classes, each linked to its canonical record. This register adds an owner and explicit operations acknowledgement; it does not copy the source facts.</p>{error&&<p role="alert" className="mt-2 text-xs text-rose-300">{error}</p>}<div className="mt-3 space-y-2">{items.length?items.map(i=><div key={i.id} className="rounded-lg border border-white/8 p-3 text-xs text-slate-300"><div className="flex justify-between gap-2"><strong className="text-slate-100">{label(i.gapClass)}</strong><span>{i.acknowledgedAt?"Seen and acknowledged by operations":"Awaiting operations acknowledgement"}</span></div><p className="mt-1 text-slate-500">Canonical reference: {i.sourceTable} / {i.sourceId} · owner {i.ownerName}{i.dueOn?` · due ${i.dueOn}`:""}</p>{canAcknowledge&&!i.acknowledgedAt&&<button onClick={()=>void acknowledge(i.id)} className="mt-2 rounded border border-signal-cyan/30 px-2 py-1 text-signal-cyan">Acknowledge for operations</button>}</div>):<p className="text-xs text-slate-500">No operational debt has been registered for this case.</p>}</div>
{canPlan&&<form onSubmit={record} className="mt-4 grid gap-2 md:grid-cols-3"><select name="candidate" required className="rounded border border-white/10 bg-overlook-deep p-2 text-xs md:col-span-3"><option value="">Select a current canonical gap…</option>{candidates.map(c=><option key={`${c.gapClass}|${c.sourceTable}|${c.sourceId}`} value={`${c.gapClass}|${c.sourceTable}|${c.sourceId}`}>{label(c.gapClass)} — {c.label}</option>)}</select><select name="owner" required className="rounded border border-white/10 bg-overlook-deep p-2 text-xs md:col-span-2"><option value="">Accountable owner…</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name??m.email??m.id}</option>)}</select><input name="due" type="date" className="rounded border border-white/10 bg-overlook-deep p-2 text-xs"/><button disabled={busy||candidates.length===0} className="rounded bg-signal-cyan px-3 py-2 text-xs font-semibold text-slate-950 disabled:opacity-50 md:col-span-3">{busy?"Registering…":"Register referenced gap"}</button></form>}</section>}
