import { FormEvent, useCallback, useEffect, useState } from "react";
import { approveCaseTechnicalDebt,getCaseTechnicalDebt,listCaseTechnicalDebtAssets,recordCaseTechnicalDebt,type TechnicalDebtRegister } from "../../services/technicalDebtService";

const kinds=["jumper","bypass","defeat","temporary_repair","software_override","alternative_part","temporary_support","deferred_redesign","incomplete_monitoring","other"];
export function TechnicalDebtPanel({caseId,canPlan,canApprove}:{caseId:string;canPlan:boolean;canApprove:boolean}){
  const [register,setRegister]=useState<TechnicalDebtRegister|null>(null); const [assets,setAssets]=useState<{id:string;name:string}[]>([]); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  const load=useCallback(()=>Promise.all([getCaseTechnicalDebt(caseId),listCaseTechnicalDebtAssets(caseId)]).then(([r,a])=>{setRegister(r);setAssets(a);}).catch(e=>setError(e instanceof Error?e.message:"Unable to load technical debt")),[caseId]);
  useEffect(()=>{void load();},[load]);
  async function record(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError(null);const f=new FormData(e.currentTarget);const v=(n:string)=>String(f.get(n)??"").trim();try{await recordCaseTechnicalDebt(caseId,{asset_id:v("asset"),modification_kind:v("kind"),description:v("description"),reason:v("reason"),required_removal_by:v("due"),risk_assessment_ref:v("risk"),lifecycle_cost:v("cost")||null,lifecycle_cost_currency:v("currency")||null,lifecycle_cost_basis:v("costBasis")||null});e.currentTarget.reset();await load();}catch(x){setError(x instanceof Error?x.message:"Recording refused");}finally{setBusy(false);}}
  async function approve(id:number){const basis=window.prompt("State the independent approval evidence basis (minimum 20 characters):");if(!basis)return;try{await approveCaseTechnicalDebt(id,basis);await load();}catch(x){setError(x instanceof Error?x.message:"Approval refused");}}
  return <section className="rounded-xl border border-white/6 bg-[#0D1520] p-5"><h2 className="text-sm font-semibold text-white">Technical debt</h2><p className="mt-1 text-xs text-slate-400">Known imperfect choices linked to this case. Unknown lifecycle cost stays unvalued—not zero. Recording never substitutes for independent approval.</p>
    {error&&<p role="alert" className="mt-2 text-xs text-rose-300">{error}</p>}
    <div className="mt-3 space-y-2">{register?.items.length?register.items.map(i=><div key={i.id} className="rounded-lg border border-white/8 p-3 text-xs text-slate-300"><div className="flex justify-between gap-3"><strong className="text-slate-100">{i.assetName} · {i.kind.replaceAll("_"," ")}</strong><span>{i.approvedAt?"Approved":"Awaiting independent approval"}</span></div><p className="mt-1">{i.description}</p><p className="mt-1 text-slate-500">Remove by {i.requiredRemovalBy} · risk {i.riskAssessmentRef} · {i.lifecycleCost==null?"lifecycle cost unvalued":`${i.lifecycleCost} ${i.currency} — ${i.costBasis}`}</p>{canApprove&&!i.approvedAt&&!i.removedAt&&<button className="mt-2 rounded border border-signal-cyan/30 px-2 py-1 text-signal-cyan" onClick={()=>void approve(i.id)}>Approve independently</button>}</div>):<p className="text-xs text-slate-500">No technical debt has been recorded for this case.</p>}</div>
    {register&&<p className="mt-2 text-[11px] text-slate-500">{register.unvaluedCount} unvalued item(s). {register.note}</p>}
    {canPlan&&<form onSubmit={record} className="mt-4 grid gap-2 md:grid-cols-2"><select required name="asset" className="rounded border border-white/10 bg-overlook-deep p-2 text-xs"><option value="">Case asset…</option>{assets.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select required name="kind" className="rounded border border-white/10 bg-overlook-deep p-2 text-xs"><option value="">Debt kind…</option>{kinds.map(k=><option key={k}>{k}</option>)}</select><textarea required minLength={20} name="description" placeholder="Known imperfect condition (20+ characters)" className="rounded border border-white/10 bg-overlook-deep p-2 text-xs"/><textarea required minLength={20} name="reason" placeholder="Why it is being accepted temporarily (20+ characters)" className="rounded border border-white/10 bg-overlook-deep p-2 text-xs"/><input required name="due" type="date" className="rounded border border-white/10 bg-overlook-deep p-2 text-xs"/><input required name="risk" placeholder="Controlled risk assessment reference" className="rounded border border-white/10 bg-overlook-deep p-2 text-xs"/><input name="cost" type="number" min="0" step="any" placeholder="Lifecycle cost (optional)" className="rounded border border-white/10 bg-overlook-deep p-2 text-xs"/><input name="currency" maxLength={3} placeholder="ISO currency with cost" className="rounded border border-white/10 bg-overlook-deep p-2 text-xs"/><textarea name="costBasis" minLength={20} placeholder="Cost source and basis, required with cost" className="rounded border border-white/10 bg-overlook-deep p-2 text-xs md:col-span-2"/><button disabled={busy||assets.length===0} className="rounded bg-signal-cyan px-3 py-2 text-xs font-semibold text-slate-950 disabled:opacity-50 md:col-span-2">{busy?"Recording…":"Record for independent approval"}</button></form>}
  </section>;
}
