import { type ElementType, useEffect, useMemo, useState } from "react";
import { CheckCircle2, ClipboardCheck, FileSearch, FileText, Gauge, LogOut, ShieldCheck, Target, Upload, Users, Workflow } from "lucide-react";
import { supabase } from "../lib/supabase";
import { platformService, type UserContext } from "../services/platform";
import { approveRiaCriticalityItem, loadRiaWorkspace, publishRiaFinding, uploadRiaSource, type RiaWorkspaceData } from "../services/riaAssessment";

type Tab = "home"|"data"|"evidence"|"baseline"|"findings"|"opportunities"|"decisions"|"plan"|"report"|"verification";
const tabs:Array<{id:Tab;label:string;icon:ElementType}> = [
  {id:"home",label:"Assessment Home",icon:ClipboardCheck},{id:"data",label:"Data Room",icon:Upload},{id:"evidence",label:"Evidence Explorer",icon:FileSearch},{id:"baseline",label:"Reliability Baseline",icon:Gauge},{id:"findings",label:"Findings & Bad Actors",icon:Target},{id:"opportunities",label:"Opportunity Register",icon:Workflow},{id:"decisions",label:"Decision Board",icon:Users},{id:"plan",label:"90-Day Plan",icon:CheckCircle2},{id:"report",label:"Executive Report",icon:FileText},{id:"verification",label:"Verification",icon:ShieldCheck},
];
const sourceCategories = [["asset_register","Asset register"],["work_orders","Work-order history"],["pm_plans","PM plans / task library"],["downtime_meter","Downtime / meter history"],["dealer_oem","Dealer / OEM records"],["operating_measure","Utilization / production / OEE"]] as const;
const requiredCategories = new Set(["asset_register","work_orders","pm_plans","downtime_meter"]);

function gradeClass(grade:string) { if (["supported","approved","published"].includes(grade)) return "border-emerald-300/20 bg-emerald-300/5 text-emerald-200"; if (grade.includes("partial") || grade === "conflict") return "border-amber-300/20 bg-amber-300/5 text-amber-200"; return "border-white/10 bg-white/[0.02] text-slate-300"; }
function money(low:number|null, high:number|null, currency:string|null) { if (low == null && high == null) return "Not quantified"; const f = (n:number) => new Intl.NumberFormat("en-US",{style:"currency",currency:currency || "USD",maximumFractionDigits:0}).format(n); return low != null && high != null ? `${f(low)}–${f(high)}` : f((low ?? high)!); }

export function RiaAssessmentWorkspacePage() {
  const [context,setContext] = useState<UserContext|null>(null);
  const [workspace,setWorkspace] = useState<RiaWorkspaceData|null>(null);
  const [loading,setLoading] = useState(true);
  const [error,setError] = useState("");
  const [tab,setTab] = useState<Tab>("home");
  const [category,setCategory] = useState("work_orders");
  const [uploading,setUploading] = useState(false);
  const [selectedSource,setSelectedSource] = useState<string|null>(null);

  const refresh = async (ctx = context) => { if (ctx?.organization_id) setWorkspace(await loadRiaWorkspace(ctx.organization_id)); };
  useEffect(() => { (async () => { try { const { data:{ session } } = await supabase.auth.getSession(); if (!session) return; const ctx = await platformService.getCurrentUserContext(); setContext(ctx); if (ctx?.organization_id) setWorkspace(await loadRiaWorkspace(ctx.organization_id)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load assessment workspace."); } finally { setLoading(false); } })(); }, []);
  useEffect(() => { document.title = "Reliability Intelligence Assessment Workspace | SyncAI"; }, []);

  const readiness = useMemo(() => { if (!workspace) return 0; const present = new Set(workspace.sources.filter(s => ["uploaded","profiled","accepted"].includes(s.status)).map(s => s.category)); return Math.round(([...requiredCategories].filter(c => present.has(c)).length / requiredCategories.size) * 100); }, [workspace]);
  const sourceMap = useMemo(() => new Map((workspace?.sources || []).map(s => [s.id,s])),[workspace]);

  if (loading) return <main className="min-h-screen bg-[#081018] p-8 text-slate-300">Loading governed assessment workspace…</main>;
  if (!context) return <main className="min-h-screen bg-[#081018] px-6 py-24 text-white"><div className="mx-auto max-w-2xl rounded-2xl border border-white/10 bg-[#0B151F] p-8"><h1 className="text-3xl font-semibold">Sign in to your assessment workspace</h1><p className="mt-4 text-slate-400">Paid assessment workspaces are tenant-scoped and are not exposed through the public Reliability Engineer session.</p><a href="/signin?returnTo=/pilot/reliability" className="mt-7 inline-flex rounded-lg bg-teal-300 px-5 py-3 font-semibold text-slate-950">Sign in</a></div></main>;
  if (error) return <main className="min-h-screen bg-[#081018] px-6 py-24 text-white"><div className="mx-auto max-w-2xl rounded-2xl border border-red-300/20 bg-red-300/5 p-8"><h1 className="text-2xl font-semibold">Assessment workspace unavailable</h1><p className="mt-3 text-slate-300">{error}</p></div></main>;
  if (!workspace) return <main className="min-h-screen bg-[#081018] px-6 py-24 text-white"><div className="mx-auto max-w-3xl rounded-2xl border border-white/10 bg-[#0B151F] p-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-300">{context.organization_name}</p><h1 className="mt-3 text-3xl font-semibold">No Reliability Intelligence Assessment is activated for this organization.</h1><p className="mt-4 leading-7 text-slate-400">An assessment workspace is provisioned after scope and commercial acceptance. Evaluation accounts do not automatically receive a paid RIA workspace.</p><div className="mt-7 flex gap-3"><a href="https://syncai.ca/reliability-assessment" className="rounded-lg bg-teal-300 px-5 py-3 font-semibold text-slate-950">Review assessment offer</a><a href="/demo/copilot" className="rounded-lg border border-white/15 px-5 py-3 font-semibold">Reliability Engineer</a></div></div></main>;

  const openEvidence = (id:string) => { setSelectedSource(id); setTab("data"); };
  const doUpload = async (file:File|null) => { if (!file) return; setUploading(true); setError(""); try { await uploadRiaSource(context.organization_id, workspace.assessment.id, category, file); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Upload failed"); } finally { setUploading(false); } };
  const signOut = async () => { await platformService.signOut(); window.location.assign("/demo/copilot"); };

  return <main className="min-h-screen bg-[#081018] text-slate-100"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#081018]/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1500px] items-center justify-between px-5"><div><p className="text-sm font-bold text-white">SyncAI · Reliability Intelligence Assessment</p><p className="text-xs text-slate-500">{context.organization_name} · {workspace.assessment.scope_label}</p></div><div className="flex items-center gap-3"><span className="hidden rounded-full border border-white/10 px-3 py-1 text-xs text-slate-400 sm:inline">{workspace.assessment.commercial_model}</span><button onClick={signOut} className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><LogOut size={15}/>Sign out</button></div></div></header><div className="mx-auto grid max-w-[1500px] lg:grid-cols-[260px_1fr]"><aside className="border-r border-white/10 p-4 lg:min-h-[calc(100vh-4rem)]"><div className="mb-5 rounded-xl border border-white/10 bg-white/[0.02] p-4"><p className="text-xs uppercase tracking-wider text-slate-500">Data readiness</p><p className="mt-2 text-3xl font-semibold text-white">{readiness}%</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-teal-300" style={{width:`${readiness}%`}}/></div><p className="mt-3 text-xs leading-5 text-slate-500">Required export categories present. This is readiness, not evidence sufficiency.</p></div><nav className="space-y-1">{tabs.map(item => { const Icon=item.icon; return <button key={item.id} onClick={() => setTab(item.id)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm ${tab===item.id?"bg-teal-300/10 text-teal-200":"text-slate-400 hover:bg-white/[0.03] hover:text-white"}`}><Icon size={16}/>{item.label}</button>; })}</nav></aside><section className="min-w-0 p-5 sm:p-8">{error && <div className="mb-5 rounded-lg border border-red-300/20 bg-red-300/5 p-3 text-sm text-red-200">{error}</div>}

{tab === "home" && <div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-300">Assessment Home</p><h1 className="mt-3 text-4xl font-semibold tracking-tight text-white">{workspace.assessment.name}</h1><p className="mt-4 max-w-3xl leading-7 text-slate-400">A bounded workspace for source intake, evidence integrity, reliability baseline, human-reviewed findings, decisions, and 30/60/90-day value verification.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Sources",workspace.sources.length],["Published findings",workspace.findings.filter(f=>f.review_state==="published").length],["Open decisions",workspace.decisions.filter(d=>d.status==="pending").length],["Verification records",workspace.verifications.length]].map(([label,value])=><div key={String(label)} className="rounded-xl border border-white/10 bg-[#0B151F] p-5"><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold text-white">{value}</p></div>)}</div><div className="mt-8 grid gap-5 lg:grid-cols-2"><div className="rounded-xl border border-white/10 p-6"><h2 className="font-semibold text-white">Evidence Integrity Standard</h2><div className="mt-4 space-y-3 text-sm text-slate-400"><p><strong className="text-emerald-200">SUPPORTED</strong> — sufficient for the stated conclusion, subject to authority.</p><p><strong className="text-amber-200">PARTIALLY SUPPORTED</strong> — useful for prioritization; close the named gap before irreversible action.</p><p><strong className="text-slate-200">UNSUPPORTED</strong> — do not decide from the metric or conclusion.</p></div></div><div className="rounded-xl border border-white/10 p-6"><h2 className="font-semibold text-white">Human publishing gate</h2><p className="mt-3 text-sm leading-6 text-slate-400">AI/analyst work can draft findings. Material engineering conclusions are not customer-published until an authorized Reliability Engineer or administrator records review.</p></div></div></div>}

{tab === "data" && <div><h1 className="text-3xl font-semibold text-white">Data Room</h1><p className="mt-3 text-slate-400">Upload customer-authorized exports into this tenant-scoped assessment bucket. The public demo is not used for assessment source files.</p><div className="mt-6 flex flex-col gap-3 rounded-xl border border-white/10 bg-[#0B151F] p-5 sm:flex-row sm:items-end"><label className="flex-1 text-sm text-slate-300">Source category<select value={category} onChange={e=>setCategory(e.target.value)} className="mt-2 w-full rounded-lg border border-white/10 bg-[#081018] px-3 py-3 text-white">{sourceCategories.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="inline-flex cursor-pointer items-center justify-center gap-2 rounded-lg bg-teal-300 px-5 py-3 text-sm font-semibold text-slate-950"><Upload size={16}/>{uploading?"Uploading…":"Choose export"}<input type="file" className="hidden" disabled={uploading} onChange={e=>void doUpload(e.target.files?.[0]||null)}/></label></div><div className="mt-6 space-y-3">{workspace.sources.length===0 && <p className="rounded-xl border border-dashed border-white/10 p-8 text-center text-slate-500">No assessment source files uploaded yet.</p>}{workspace.sources.map(source=><div key={source.id} className={`rounded-xl border p-4 ${selectedSource===source.id?"border-teal-300/40 bg-teal-300/5":"border-white/10 bg-white/[0.01]"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium text-white">{source.file_name}</p><p className="mt-1 text-xs text-slate-500">{sourceCategories.find(x=>x[0]===source.category)?.[1] || source.category} · {source.record_count == null ? "record count not profiled" : `${source.record_count.toLocaleString()} records`}</p></div><span className={`rounded-full border px-2.5 py-1 text-xs ${gradeClass(source.quality_grade)}`}>{source.quality_grade}</span></div></div>)}</div></div>}

{tab === "evidence" && <div><h1 className="text-3xl font-semibold text-white">Evidence Explorer</h1><p className="mt-3 text-slate-400">Trace findings back to their governed source records. Material findings should reach source evidence in two clicks or fewer.</p><div className="mt-6 space-y-4">{workspace.findings.map(f=><div key={f.id} className="rounded-xl border border-white/10 p-5"><div className="flex flex-wrap gap-2"><span className={`rounded-full border px-2.5 py-1 text-xs ${gradeClass(f.evidence_grade)}`}>{f.evidence_grade.replaceAll("_"," ")}</span><span className="rounded-full border border-white/10 px-2.5 py-1 text-xs text-slate-400">{f.severity} severity · {f.confidence} confidence</span></div><h2 className="mt-4 font-semibold text-white">{f.title}</h2><p className="mt-2 text-sm leading-6 text-slate-300">{f.statement}</p><p className="mt-3 text-sm text-slate-500"><strong>Decision boundary:</strong> {f.decision_boundary}</p><div className="mt-4 flex flex-wrap gap-2">{f.evidence_refs.length===0?<span className="text-xs text-slate-600">No source references attached</span>:f.evidence_refs.map(id=>{const s=sourceMap.get(id);return <button key={id} onClick={()=>openEvidence(id)} className="rounded-md border border-teal-300/20 bg-teal-300/5 px-3 py-1.5 text-xs text-teal-200">{s?.file_name || `Source ${id.slice(0,8)}`}</button>})}</div></div>)}</div></div>}

{tab === "baseline" && <div><h1 className="text-3xl font-semibold text-white">Reliability Baseline</h1><p className="mt-3 text-slate-400">Only metrics supported by the available data should be used in the executive baseline.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{workspace.metrics.length===0?<p className="text-slate-500">No reviewed baseline metrics yet.</p>:workspace.metrics.map(m=><div key={m.id} className="rounded-xl border border-white/10 p-5"><div className="flex justify-between gap-3"><p className="font-medium text-white">{m.label}</p><span className={`rounded-full border px-2 py-1 text-xs ${gradeClass(m.evidence_grade)}`}>{m.evidence_grade.replaceAll("_"," ")}</span></div><p className="mt-3 text-3xl font-semibold text-white">{m.value_text || "Not supportable"}{m.unit?` ${m.unit}`:""}</p><p className="mt-2 text-xs leading-5 text-slate-500">{m.method || "Method not yet reviewed."}</p></div>)}</div><div className="mt-8"><h2 className="text-xl font-semibold text-white">Criticality register</h2><div className="mt-4 space-y-3">{workspace.criticality.map(c=><div key={c.id} className="rounded-xl border border-white/10 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium text-white">{c.asset_ref?`${c.asset_ref} · `:""}{c.asset_name}</p><p className="mt-1 text-sm text-slate-400">{c.rationale}</p></div><div className="flex items-center gap-2"><span className="rounded-full border border-white/10 px-2 py-1 text-xs text-slate-300">{c.criticality}</span>{c.review_state!=="approved" && <button onClick={async()=>{try{await approveRiaCriticalityItem(c.id);await refresh();}catch(e){setError(e instanceof Error?e.message:"Approval failed")}}} className="rounded-md bg-teal-300 px-3 py-1.5 text-xs font-semibold text-slate-950">Approve</button>}</div></div></div>)}</div></div></div>}

{tab === "findings" && <div><h1 className="text-3xl font-semibold text-white">Findings & Bad Actors</h1><p className="mt-3 text-slate-400">Severity and confidence remain separate. Publishing is a human engineering action.</p><div className="mt-6 space-y-4">{workspace.findings.length===0?<p className="text-slate-500">No findings drafted yet.</p>:workspace.findings.map(f=><div key={f.id} className="rounded-xl border border-white/10 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-white">{f.title}</p><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">{f.statement}</p></div><span className={`rounded-full border px-2.5 py-1 text-xs ${gradeClass(f.review_state)}`}>{f.review_state}</span></div><div className="mt-4 flex flex-wrap gap-2 text-xs text-slate-400"><span>{f.severity} severity</span><span>·</span><span>{f.confidence} confidence</span><span>·</span><span>{f.evidence_grade.replaceAll("_"," ")}</span></div>{f.review_state!=="published" && <button onClick={async()=>{try{await publishRiaFinding(f.id);await refresh();}catch(e){setError(e instanceof Error?e.message:"Publish failed")}}} className="mt-4 rounded-lg bg-teal-300 px-4 py-2 text-sm font-semibold text-slate-950">Review & publish finding</button>}</div>)}</div></div>}

{tab === "opportunities" && <div><h1 className="text-3xl font-semibold text-white">Reliability Opportunity Register</h1><p className="mt-3 text-slate-400">Value is represented as a governed estimate or range, never manufactured precision.</p><div className="mt-6 grid gap-4 lg:grid-cols-2">{workspace.opportunities.length===0?<p className="text-slate-500">No opportunities registered yet.</p>:workspace.opportunities.map(o=><div key={o.id} className="rounded-xl border border-white/10 p-5"><div className="flex justify-between gap-3"><p className="font-semibold text-white">{o.title}</p><span className="text-xs text-slate-400">{o.priority}</span></div><p className="mt-3 text-sm leading-6 text-slate-400">{o.rationale}</p><p className="mt-5 text-2xl font-semibold text-white">{money(o.value_low,o.value_high,o.value_currency)}</p><p className="mt-1 text-xs text-slate-500">{o.confidence} confidence · {o.method || "method to be documented"}</p></div>)}</div></div>}

{tab === "decisions" && <div><h1 className="text-3xl font-semibold text-white">Decision Board</h1><p className="mt-3 text-slate-400">Each decision records recommendation, uncertainty, authority, boundary, and verification.</p><div className="mt-6 space-y-4">{workspace.decisions.length===0?<p className="text-slate-500">No management decisions queued yet.</p>:workspace.decisions.map(d=><div key={d.id} className="rounded-xl border border-white/10 p-5"><div className="flex justify-between gap-3"><h2 className="font-semibold text-white">{d.decision_required}</h2><span className={`rounded-full border px-2 py-1 text-xs ${gradeClass(d.status)}`}>{d.status}</span></div><p className="mt-3 text-sm text-slate-300"><strong>Recommendation:</strong> {d.recommendation}</p><p className="mt-2 text-sm text-slate-400"><strong>Authority:</strong> {d.authority_role}</p><p className="mt-2 text-sm text-slate-400"><strong>Boundary:</strong> {d.boundary}</p><p className="mt-2 text-sm text-slate-500"><strong>Verification:</strong> {d.verification}</p></div>)}</div></div>}

{tab === "plan" && <div><h1 className="text-3xl font-semibold text-white">90-Day Action Plan</h1><div className="mt-6 grid gap-5 lg:grid-cols-3">{(["day_30","day_60","day_90"] as const).map(h=><div key={h} className="rounded-xl border border-white/10 p-5"><h2 className="font-semibold text-white">{h.replace("day_","Day ")}</h2><div className="mt-4 space-y-3">{workspace.actions.filter(a=>a.horizon===h).map(a=><div key={a.id} className="rounded-lg bg-white/[0.02] p-3"><p className="text-sm text-slate-200">{a.action}</p><p className="mt-2 text-xs text-slate-500">{a.owner || "Owner unassigned"} · {a.status.replaceAll("_"," ")}</p>{a.verification_metric && <p className="mt-1 text-xs text-slate-600">Verify: {a.verification_metric}</p>}</div>)}{workspace.actions.filter(a=>a.horizon===h).length===0 && <p className="text-sm text-slate-600">No actions yet.</p>}</div></div>)}</div></div>}

{tab === "report" && <div><div className="flex items-center justify-between gap-4"><div><h1 className="text-3xl font-semibold text-white">Executive Report</h1><p className="mt-3 text-slate-400">Management view assembled only from the governed workspace state.</p></div><button onClick={()=>window.print()} className="rounded-lg border border-white/15 px-4 py-2 text-sm font-semibold">Print / save PDF</button></div><div className="mt-7 rounded-xl border border-white/10 bg-white p-7 text-slate-900"><p className="text-xs font-semibold uppercase tracking-wider text-teal-700">SyncAI Reliability Intelligence Assessment</p><h2 className="mt-2 text-2xl font-bold">{workspace.assessment.scope_label}</h2><p className="mt-4 text-sm text-slate-600">Data readiness: {readiness}%. Published findings: {workspace.findings.filter(f=>f.review_state==="published").length}. Open decisions: {workspace.decisions.filter(d=>d.status==="pending").length}.</p><h3 className="mt-7 font-bold">Published findings</h3><div className="mt-3 space-y-3">{workspace.findings.filter(f=>f.review_state==="published").map(f=><div key={f.id} className="border-t border-slate-200 pt-3"><p className="font-semibold">{f.title}</p><p className="mt-1 text-sm text-slate-600">{f.statement}</p><p className="mt-1 text-xs text-slate-500">Evidence: {f.evidence_grade.replaceAll("_"," ")} · Severity: {f.severity} · Confidence: {f.confidence}</p></div>)}{workspace.findings.filter(f=>f.review_state==="published").length===0 && <p className="text-sm text-slate-500">No findings have passed the human publishing gate.</p>}</div></div></div>}

{tab === "verification" && <div><h1 className="text-3xl font-semibold text-white">30 / 60 / 90-Day Verification</h1><p className="mt-3 text-slate-400">Compare outcomes with the approved baseline and record what the evidence actually supports.</p><div className="mt-6 space-y-4">{workspace.verifications.length===0?<p className="text-slate-500">Verification records will appear as the action plan reaches its checkpoints.</p>:workspace.verifications.map(v=><div key={v.id} className="rounded-xl border border-white/10 p-5"><div className="flex justify-between gap-3"><p className="font-semibold text-white">{v.checkpoint.replace("day_","Day ")} · {v.metric}</p><span className={`rounded-full border px-2 py-1 text-xs ${gradeClass(v.status)}`}>{v.status.replaceAll("_"," ")}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><p className="text-sm text-slate-400"><strong>Baseline:</strong> {v.baseline || "Not established"}</p><p className="text-sm text-slate-400"><strong>Observed:</strong> {v.observed || "Not measured"}</p></div><p className="mt-3 text-xs leading-5 text-slate-500">Method: {v.method}</p></div>)}</div></div>}

</section></div></main>;
}
