#!/usr/bin/env bash
set -euo pipefail
trap 'echo "Safety obligation register smoke FAILED at line $LINENO: $BASH_COMMAND"' ERR
psqlc(){ PGPASSWORD=postgres psql -h 127.0.0.1 -p 54322 -U postgres -d postgres -qAt -v ON_ERROR_STOP=1 -c "$1"; }
eval "$(supabase status -o env | grep -E '^(ANON_KEY|API_URL)=')"; : "${API_URL:?}" "${ANON_KEY:?}"
ORG='11111111-1111-1111-1111-111111111111'; OTHER='99999999-9999-9999-9999-999999999918'
MAIN_CASE='98800000-0000-0000-0000-000000000001'; OTHER_SITE='98800000-0000-0000-0000-000000000002'; OTHER_ASSET='98800000-0000-0000-0000-000000000003'; OTHER_CASE='98800000-0000-0000-0000-000000000004'
EVIDENCE='98800000-0000-0000-0000-000000000021'; UNVERIFIED='98800000-0000-0000-0000-000000000022'; FOREIGN_EVIDENCE='98800000-0000-0000-0000-000000000023'
token(){ curl -sS "$API_URL/auth/v1/token?grant_type=password" -H "apikey: $ANON_KEY" -H 'content-type: application/json' -d "{\"email\":\"$1\",\"password\":\"$2\"}"|python3 -c "import json,sys;print(json.load(sys.stdin).get('access_token',''))"; }
rpc(){ curl -sS -w '\n%{http_code}' -X POST "$API_URL/rest/v1/rpc/$2" -H "apikey: $ANON_KEY" -H "authorization: Bearer $1" -H 'content-type: application/json' -d "$3"; }
body(){ printf '%s' "${1%$'\n'*}"; }; status(){ printf '%s' "${1##*$'\n'}"; }
ok(){ test "$(status "$1")" = 200; BODY="$(body "$1")" python3 -c "import json,os;x=json.loads(os.environ['BODY']);assert 'error' not in x,x"; }
err(){ test "$(status "$1")" = 200; BODY="$(body "$1")" NEEDLE="$2" python3 -c "import json,os;x=json.loads(os.environ['BODY']);assert os.environ['NEEDLE'] in x.get('error',''),x"; }
ENGINEER=$(token 'demo@syncai.ca' 'Demo123!@#'); ADMIN=$(token 'admin@syncai.ca' 'Admin123!@#'); test -n "$ENGINEER"; test -n "$ADMIN"
psqlc "insert into development_cases(id,organization_id,title,lifecycle_type,problem_statement,status,created_by) values('$MAIN_CASE','$ORG','C2.11 safety obligation case','regulatory','Determine which current regulatory obligations apply to the named safety-critical elements.','active',(select id from auth.users where email='demo@syncai.ca')) on conflict(id) do nothing"
ASSET=$(psqlc "select id from assets where organization_id='$ORG' order by created_at limit 1"); CASE_ID=$(psqlc "select id from development_cases where id='$MAIN_CASE' and organization_id='$ORG'"); SCE=$(psqlc "select id from safety_critical_elements where organization_id='$ORG' order by id limit 1")
test -n "$ASSET"; test -n "$CASE_ID"; test -n "$SCE"
REQ=$(psqlc "with x as (insert into regulatory_requirements(organization_id,development_case_id,requirement_ref,regulator,jurisdiction,instrument,permit_type,description,source_authority,trigger_condition,expected_lead_time_days,created_by) values('$ORG','$CASE_ID','C2.11-CI-REQ','CI Energy Regulator','Alberta','CI Safety Regulation','Operating authorization','Maintain the named safety-critical barrier within its approved performance standard.','REGULATION','Operation of the regulated facility',30,(select id from auth.users where email='demo@syncai.ca')) on conflict(organization_id,requirement_ref) do update set description=excluded.description returning id) select id from x")
psqlc "insert into organizations(id,name,industry,org_level) values('$OTHER','C2.11 foreign','utilities','enterprise') on conflict(id) do nothing"
psqlc "insert into sites(id,organization_id,name) values('$OTHER_SITE','$OTHER','C2.11 foreign site') on conflict(id) do nothing"
psqlc "insert into assets(id,organization_id,site_id,name) values('$OTHER_ASSET','$OTHER','$OTHER_SITE','C2.11 foreign asset') on conflict(id) do nothing"
psqlc "insert into development_cases(id,organization_id,title,lifecycle_type,problem_statement,status) values('$OTHER_CASE','$OTHER','Foreign regulatory case','regulatory','Foreign tenant case used only to prove the C2.11 tenant wall.','active') on conflict(id) do nothing"
OTHER_SCE=$(psqlc "with x as(insert into safety_critical_elements(organization_id,asset_id,sce_ref,label,barrier_kind,barrier_role,performance_standard) values('$OTHER','$OTHER_ASSET','C2.11-FOREIGN-SCE','Foreign shutdown barrier','instrumented','preventive','Foreign approved performance standard not visible to the primary tenant.') on conflict(organization_id,sce_ref) do update set label=excluded.label returning id) select id from x")
OTHER_REQ=$(psqlc "with x as(insert into regulatory_requirements(organization_id,development_case_id,requirement_ref,regulator,jurisdiction,instrument,permit_type,description,source_authority,trigger_condition,expected_lead_time_days) values('$OTHER','$OTHER_CASE','C2.11-FOREIGN-REQ','Foreign Regulator','Foreign jurisdiction','Foreign regulation','Foreign permit','Foreign obligation must not cross the tenant wall.','REGULATION','Foreign operation',30) on conflict(organization_id,requirement_ref) do update set description=excluded.description returning id) select id from x")
psqlc "insert into evidence_items(id,organization_id,asset_id,source_system,evidence_type,description,evidence_class) values('$EVIDENCE','$ORG','$ASSET','ci-c2-11','approved_inspection','Verified applicability evidence for the safety-critical regulatory obligation.','DOCUMENTED'),('$UNVERIFIED','$ORG','$ASSET','ci-c2-11','documented','Unverified evidence cannot support a determinate applicability claim.','DOCUMENTED') on conflict(id) do nothing"
psqlc "insert into evidence_items(id,organization_id,asset_id,source_system,evidence_type,description,evidence_class) values('$FOREIGN_EVIDENCE','$OTHER','$OTHER_ASSET','ci-c2-11','documented','Foreign evidence must remain inaccessible.','DOCUMENTED') on conflict(id) do nothing"
VERIFY=$(rpc "$ADMIN" verify_evidence_item "{\"p_evidence_id\":\"$EVIDENCE\",\"p_method\":\"Independent C2.11 applicability review\",\"p_outcome\":\"verified\",\"p_note\":\"Identity, source authority, barrier applicability and current revision independently confirmed.\"}"); ok "$VERIFY"
NO_EVIDENCE=$(rpc "$ENGINEER" save_safety_critical_obligation "{\"p_sce_id\":$SCE,\"p_requirement_id\":$REQ,\"p_applicability_status\":\"applicable\",\"p_basis\":\"The regulated barrier is explicitly named by the operating authorization.\"}"); err "$NO_EVIDENCE" 'requires verified canonical evidence'
UNVERIFIED_RESULT=$(rpc "$ENGINEER" save_safety_critical_obligation "{\"p_sce_id\":$SCE,\"p_requirement_id\":$REQ,\"p_applicability_status\":\"applicable\",\"p_basis\":\"The regulated barrier is explicitly named by the operating authorization.\",\"p_evidence_item_ids\":[\"$UNVERIFIED\"]}"); err "$UNVERIFIED_RESULT" 'independently verified'
UNDETERMINED=$(rpc "$ENGINEER" save_safety_critical_obligation "{\"p_sce_id\":$SCE,\"p_requirement_id\":$REQ,\"p_applicability_status\":\"undetermined\",\"p_basis\":\"Applicability remains open pending the current permit schedule and asset cross-reference.\",\"p_missing_evidence\":[\"Current permit equipment schedule\"]}"); ok "$UNDETERMINED"
APPLICABLE=$(rpc "$ENGINEER" save_safety_critical_obligation "{\"p_sce_id\":$SCE,\"p_requirement_id\":$REQ,\"p_applicability_status\":\"applicable\",\"p_basis\":\"Verified permit schedule explicitly identifies this safety-critical element.\",\"p_evidence_item_ids\":[\"$EVIDENCE\"]}"); ok "$APPLICABLE"
FOREIGN_SCE_RESULT=$(rpc "$ENGINEER" save_safety_critical_obligation "{\"p_sce_id\":$OTHER_SCE,\"p_requirement_id\":$REQ,\"p_applicability_status\":\"undetermined\",\"p_basis\":\"Cross-tenant safety elements must never be linkable.\",\"p_missing_evidence\":[\"Tenant-owned applicability evidence\"]}"); err "$FOREIGN_SCE_RESULT" 'not found in this organization'
FOREIGN_REQ_RESULT=$(rpc "$ENGINEER" save_safety_critical_obligation "{\"p_sce_id\":$SCE,\"p_requirement_id\":$OTHER_REQ,\"p_applicability_status\":\"undetermined\",\"p_basis\":\"Cross-tenant requirements must never be linkable.\",\"p_missing_evidence\":[\"Tenant-owned applicability evidence\"]}"); err "$FOREIGN_REQ_RESULT" 'not found in this organization'
FOREIGN_EVIDENCE_RESULT=$(rpc "$ENGINEER" save_safety_critical_obligation "{\"p_sce_id\":$SCE,\"p_requirement_id\":$REQ,\"p_applicability_status\":\"applicable\",\"p_basis\":\"Cross-tenant evidence must never support applicability.\",\"p_evidence_item_ids\":[\"$FOREIGN_EVIDENCE\"]}"); err "$FOREIGN_EVIDENCE_RESULT" 'belong to this organization'
WORKSPACE=$(rpc "$ENGINEER" get_safety_obligation_register '{}'); ok "$WORKSPACE"
BODY="$(body "$WORKSPACE")" SCE="$SCE" REQ="$REQ" OTHER_SCE="$OTHER_SCE" OTHER_REQ="$OTHER_REQ" python3 -c "import json,os;x=json.loads(os.environ['BODY']);assert any(str(a['id'])==os.environ['SCE'] for a in x['elements']);assert any(str(r['id'])==os.environ['REQ'] for r in x['requirements']);assert any(str(l['sce_id'])==os.environ['SCE'] and str(l['requirement_id'])==os.environ['REQ'] and l['applicability_status']=='applicable' for l in x['links']);assert all(str(a['id'])!=os.environ['OTHER_SCE'] for a in x['elements']);assert all(str(r['id'])!=os.environ['OTHER_REQ'] for r in x['requirements']);assert 'applicability only' in x['authority_boundary'].lower()"
DIRECT=$(curl -sS -o /tmp/c2-11-direct.txt -w '%{http_code}' -X POST "$API_URL/rest/v1/safety_critical_element_obligations" -H "apikey: $ANON_KEY" -H "authorization: Bearer $ENGINEER" -H 'content-type: application/json' -d "{\"organization_id\":\"$ORG\",\"sce_id\":$SCE,\"requirement_id\":$REQ,\"applicability_status\":\"undetermined\",\"basis\":\"Unauthorized direct write must be refused.\",\"missing_evidence\":[\"Missing\"],\"linked_by\":\"00000000-0000-0000-0000-000000000001\"}")
test "$DIRECT" = 401 -o "$DIRECT" = 403
test "$(psqlc "select count(*) from audit_events where organization_id='$ORG' and entity_type='safety_critical_obligation' and event_data->>'sce_id'='$SCE'")" -ge 2
echo 'Safety obligation register smoke passed: canonical_edge=true tenant_wall=true verified_evidence=true undetermined_gap=true audit=true direct_write_closed=true authority_unchanged=true'
