/**
 * Generate the relational industry-pack membership migration from the
 * canonical TypeScript pack library.
 *
 * Counts shown in deployment surfaces are derived from these rows. Do not
 * type a count into SQL: change the canonical pack and regenerate instead.
 *
 *   npx tsx scripts/generate-industry-pack-membership.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { INDUSTRY_TEMPLATE_PACKS } from "../src/lib/industry-template-packs";

const target =
  "supabase/migrations/20261002091000_industry_pack_membership.sql";

// This generator protects the already-deployed base snapshot. New packs are
// appended in later immutable migrations; they must not rewrite this file.
const BASE_MIGRATION_PACKS = Object.values(INDUSTRY_TEMPLATE_PACKS).filter(
  (pack) =>
    !["battery_energy_storage", "healthcare"].includes(pack.industryCode),
);

const lit = (value: string) => `'${value.replace(/'/g, "''")}'`;
const key = (value: string) =>
  value
    .normalize("NFKD")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase()
    .slice(0, 120);

export function renderIndustryPackMembershipMigration(): string {
  for (const pack of BASE_MIGRATION_PACKS) {
    for (const [kind, labels] of [
      ["KPI", [...pack.kpiModel.primaryKpis, ...pack.kpiModel.secondaryKpis]],
      ["asset class", pack.commonAssetClasses],
      ["failure mode", pack.failureModeFocusAreas],
    ] as const) {
      const keys = labels.map(key);
      if (new Set(keys).size !== keys.length) {
        throw new Error(
          `${pack.industryCode} contains colliding ${kind} membership keys`,
        );
      }
    }
  }

  const out: string[] = [
    "-- GENERATED by scripts/generate-industry-pack-membership.ts — do not edit by hand.",
    "-- Source of truth: src/lib/industry-template-packs.ts.",
    "-- Counts are derived from relational membership and are never asserted literals.",
    "",
    "alter table public.kpi_packs add column if not exists industry_code text;",
    "alter table public.industry_asset_libraries add column if not exists industry_code text;",
    "alter table public.industry_failure_mode_packs add column if not exists industry_code text;",
    "",
    "update public.kpi_packs set industry_code = 'oil_sands' where id = '94000000-0000-0000-0000-000000000001' and industry_code is null;",
    "update public.industry_asset_libraries set industry_code = 'oil_sands' where id = '94100000-0000-0000-0000-000000000001' and industry_code is null;",
    "update public.industry_failure_mode_packs set industry_code = 'oil_sands' where id = '94400000-0000-0000-0000-000000000001' and industry_code is null;",
    "",
    "create unique index if not exists uq_kpi_packs_industry_code on public.kpi_packs(industry_code) where industry_code is not null;",
    "create unique index if not exists uq_asset_libraries_industry_code on public.industry_asset_libraries(industry_code) where industry_code is not null;",
    "create unique index if not exists uq_failure_mode_packs_industry_code on public.industry_failure_mode_packs(industry_code) where industry_code is not null;",
    "",
    "create table if not exists public.kpi_pack_items (",
    "  pack_id uuid not null references public.kpi_packs(id) on delete cascade,",
    "  item_key text not null,",
    "  label text not null,",
    "  category text not null check (category in ('primary','secondary')),",
    "  ordinal int not null check (ordinal >= 0),",
    "  source_ref text not null,",
    "  primary key (pack_id, item_key)",
    ");",
    "create table if not exists public.industry_asset_library_items (",
    "  library_id uuid not null references public.industry_asset_libraries(id) on delete cascade,",
    "  item_key text not null,",
    "  label text not null,",
    "  ordinal int not null check (ordinal >= 0),",
    "  source_ref text not null,",
    "  primary key (library_id, item_key)",
    ");",
    "create table if not exists public.failure_mode_pack_items (",
    "  pack_id uuid not null references public.industry_failure_mode_packs(id) on delete cascade,",
    "  item_key text not null,",
    "  label text not null,",
    "  ordinal int not null check (ordinal >= 0),",
    "  source_ref text not null,",
    "  primary key (pack_id, item_key)",
    ");",
    "",
    "alter table public.kpi_pack_items enable row level security;",
    "alter table public.industry_asset_library_items enable row level security;",
    "alter table public.failure_mode_pack_items enable row level security;",
    "drop policy if exists kpi_pack_items_read on public.kpi_pack_items;",
    "create policy kpi_pack_items_read on public.kpi_pack_items for select to authenticated using (true);",
    "drop policy if exists industry_asset_library_items_read on public.industry_asset_library_items;",
    "create policy industry_asset_library_items_read on public.industry_asset_library_items for select to authenticated using (true);",
    "drop policy if exists failure_mode_pack_items_read on public.failure_mode_pack_items;",
    "create policy failure_mode_pack_items_read on public.failure_mode_pack_items for select to authenticated using (true);",
    "",
    "create or replace function public.sync_kpi_pack_count() returns trigger language plpgsql security definer set search_path = public as $$",
    "declare v_pack uuid;",
    "begin",
    "  v_pack := case when tg_op = 'DELETE' then old.pack_id else new.pack_id end;",
    "  if tg_op = 'UPDATE' and old.pack_id is distinct from new.pack_id then",
    "    update public.kpi_packs set kpi_count = (select count(*) from public.kpi_pack_items where pack_id = old.pack_id) where id = old.pack_id;",
    "  end if;",
    "  update public.kpi_packs set kpi_count = (select count(*) from public.kpi_pack_items where pack_id = v_pack) where id = v_pack;",
    "  return null;",
    "end $$;",
    "drop trigger if exists trg_sync_kpi_pack_count on public.kpi_pack_items;",
    "create trigger trg_sync_kpi_pack_count after insert or delete or update of pack_id on public.kpi_pack_items for each row execute function public.sync_kpi_pack_count();",
    "",
    "create or replace function public.sync_asset_library_count() returns trigger language plpgsql security definer set search_path = public as $$",
    "declare v_library uuid;",
    "begin",
    "  v_library := case when tg_op = 'DELETE' then old.library_id else new.library_id end;",
    "  if tg_op = 'UPDATE' and old.library_id is distinct from new.library_id then",
    "    update public.industry_asset_libraries set asset_class_count = (select count(*) from public.industry_asset_library_items where library_id = old.library_id) where id = old.library_id;",
    "  end if;",
    "  update public.industry_asset_libraries set asset_class_count = (select count(*) from public.industry_asset_library_items where library_id = v_library) where id = v_library;",
    "  return null;",
    "end $$;",
    "drop trigger if exists trg_sync_asset_library_count on public.industry_asset_library_items;",
    "create trigger trg_sync_asset_library_count after insert or delete or update of library_id on public.industry_asset_library_items for each row execute function public.sync_asset_library_count();",
    "",
    "create or replace function public.sync_failure_mode_pack_count() returns trigger language plpgsql security definer set search_path = public as $$",
    "declare v_pack uuid;",
    "begin",
    "  v_pack := case when tg_op = 'DELETE' then old.pack_id else new.pack_id end;",
    "  if tg_op = 'UPDATE' and old.pack_id is distinct from new.pack_id then",
    "    update public.industry_failure_mode_packs set failure_mode_count = (select count(*) from public.failure_mode_pack_items where pack_id = old.pack_id) where id = old.pack_id;",
    "  end if;",
    "  update public.industry_failure_mode_packs set failure_mode_count = (select count(*) from public.failure_mode_pack_items where pack_id = v_pack) where id = v_pack;",
    "  return null;",
    "end $$;",
    "drop trigger if exists trg_sync_failure_mode_pack_count on public.failure_mode_pack_items;",
    "create trigger trg_sync_failure_mode_pack_count after insert or delete or update of pack_id on public.failure_mode_pack_items for each row execute function public.sync_failure_mode_pack_count();",
    "revoke all on function public.sync_kpi_pack_count() from public, anon, authenticated;",
    "revoke all on function public.sync_asset_library_count() from public, anon, authenticated;",
    "revoke all on function public.sync_failure_mode_pack_count() from public, anon, authenticated;",
    "",
  ];

  for (const pack of BASE_MIGRATION_PACKS) {
    const code = lit(pack.industryCode);
    const source = lit(
      `src/lib/industry-template-packs.ts#${pack.industryCode}`,
    );
    out.push(
      `insert into public.kpi_packs (pack_name, industry_code) values (${lit(`${pack.industryName} KPI Pack`)}, ${code})`,
      "on conflict (industry_code) where industry_code is not null do update set pack_name = excluded.pack_name;",
      `insert into public.industry_asset_libraries (library_name, industry_code) values (${lit(`${pack.industryName} Asset Library`)}, ${code})`,
      "on conflict (industry_code) where industry_code is not null do update set library_name = excluded.library_name;",
      `insert into public.industry_failure_mode_packs (pack_name, industry_code) values (${lit(`${pack.industryName} Failure Modes`)}, ${code})`,
      "on conflict (industry_code) where industry_code is not null do update set pack_name = excluded.pack_name;",
      "",
    );

    const kpis = [
      ...pack.kpiModel.primaryKpis.map((label) => ({
        label,
        category: "primary",
      })),
      ...pack.kpiModel.secondaryKpis.map((label) => ({
        label,
        category: "secondary",
      })),
    ];
    kpis.forEach((item, ordinal) =>
      out.push(
        "insert into public.kpi_pack_items (pack_id, item_key, label, category, ordinal, source_ref)",
        `select id, ${lit(key(item.label))}, ${lit(item.label)}, ${lit(item.category)}, ${ordinal}, ${source} from public.kpi_packs where industry_code = ${code}`,
        "on conflict (pack_id, item_key) do update set label = excluded.label, category = excluded.category, ordinal = excluded.ordinal, source_ref = excluded.source_ref;",
      ),
    );
    pack.commonAssetClasses.forEach((label, ordinal) =>
      out.push(
        "insert into public.industry_asset_library_items (library_id, item_key, label, ordinal, source_ref)",
        `select id, ${lit(key(label))}, ${lit(label)}, ${ordinal}, ${source} from public.industry_asset_libraries where industry_code = ${code}`,
        "on conflict (library_id, item_key) do update set label = excluded.label, ordinal = excluded.ordinal, source_ref = excluded.source_ref;",
      ),
    );
    pack.failureModeFocusAreas.forEach((label, ordinal) =>
      out.push(
        "insert into public.failure_mode_pack_items (pack_id, item_key, label, ordinal, source_ref)",
        `select id, ${lit(key(label))}, ${lit(label)}, ${ordinal}, ${source} from public.industry_failure_mode_packs where industry_code = ${code}`,
        "on conflict (pack_id, item_key) do update set label = excluded.label, ordinal = excluded.ordinal, source_ref = excluded.source_ref;",
      ),
    );
    out.push("");
  }

  out.push(
    "-- Remove membership deleted from the canonical pack on regeneration.",
    "delete from public.kpi_pack_items i using public.kpi_packs p where i.pack_id = p.id and i.source_ref like 'src/lib/industry-template-packs.ts#%' and not exists (select 1 from (values",
  );
  const kpiValues = BASE_MIGRATION_PACKS.flatMap((pack) =>
    [...pack.kpiModel.primaryKpis, ...pack.kpiModel.secondaryKpis].map(
      (label) => `    (${lit(pack.industryCode)}, ${lit(key(label))})`,
    ),
  );
  out.push(
    kpiValues.join(",\n"),
    "  ) keep(industry_code, item_key) where keep.industry_code = p.industry_code and keep.item_key = i.item_key);",
    "",
  );

  out.push(
    "delete from public.industry_asset_library_items i using public.industry_asset_libraries p where i.library_id = p.id and i.source_ref like 'src/lib/industry-template-packs.ts#%' and not exists (select 1 from (values",
  );
  const assetValues = BASE_MIGRATION_PACKS.flatMap((pack) =>
    pack.commonAssetClasses.map(
      (label) => `    (${lit(pack.industryCode)}, ${lit(key(label))})`,
    ),
  );
  out.push(
    assetValues.join(",\n"),
    "  ) keep(industry_code, item_key) where keep.industry_code = p.industry_code and keep.item_key = i.item_key);",
    "",
  );

  out.push(
    "delete from public.failure_mode_pack_items i using public.industry_failure_mode_packs p where i.pack_id = p.id and i.source_ref like 'src/lib/industry-template-packs.ts#%' and not exists (select 1 from (values",
  );
  const failureValues = BASE_MIGRATION_PACKS.flatMap((pack) =>
    pack.failureModeFocusAreas.map(
      (label) => `    (${lit(pack.industryCode)}, ${lit(key(label))})`,
    ),
  );
  out.push(
    failureValues.join(",\n"),
    "  ) keep(industry_code, item_key) where keep.industry_code = p.industry_code and keep.item_key = i.item_key);",
    "",
  );

  out.push(
    "-- Counts shown by the product are earned by the rows above.",
    "update public.kpi_packs p set kpi_count = (select count(*) from public.kpi_pack_items i where i.pack_id = p.id);",
    "update public.industry_asset_libraries p set asset_class_count = (select count(*) from public.industry_asset_library_items i where i.library_id = p.id);",
    "update public.industry_failure_mode_packs p set failure_mode_count = (select count(*) from public.failure_mode_pack_items i where i.pack_id = p.id);",
    "",
    "-- The four legacy deployment templates were all pointed at Oil Sands by a blanket update.",
    "-- Bind each known template to its own canonical pack; do not guess for unknown slugs.",
    "with binding(slug, industry_code) as (values",
    "  ('oil-sands','oil_sands'), ('mining','mining'),",
    "  ('manufacturing','manufacturing'), ('power','power_generation')",
    ")",
    "update public.deployment_templates d set",
    "  kpi_pack_id = k.id, asset_library_id = a.id, failure_mode_pack_id = f.id",
    "from binding b",
    "join public.kpi_packs k on k.industry_code = b.industry_code",
    "join public.industry_asset_libraries a on a.industry_code = b.industry_code",
    "join public.industry_failure_mode_packs f on f.industry_code = b.industry_code",
    "where d.slug = b.slug;",
    "",
    "notify pgrst, 'reload schema';",
    "",
  );

  return out.join("\n");
}

if (process.argv[1]?.endsWith("generate-industry-pack-membership.ts")) {
  const rendered = renderIndustryPackMembershipMigration();
  if (process.argv.includes("--check")) {
    const current = readFileSync(target, "utf8");
    if (current !== rendered) {
      console.error(
        `${target} is stale. Run npm run industry-packs:generate and commit the result.`,
      );
      process.exit(1);
    }
    console.log(`${target} matches the canonical industry pack library.`);
  } else {
    writeFileSync(target, rendered);
    console.log(
      `Wrote ${target} from ${Object.keys(INDUSTRY_TEMPLATE_PACKS).length} canonical packs.`,
    );
  }
}
