/**
 * Emit the asset-twin template and OEM-overlay seed migration FROM the code
 * library, rather than retyping it into SQL.
 *
 * The library in src/lib/asset-twins is the canonical definition of what an
 * asset class is. Hand-copying twelve templates into a migration would create a
 * second definition that drifts the first time somebody edits one of them. This
 * script reads the library and prints SQL, so the migration is a build product
 * and the library stays the single source.
 *
 * Templates land at maturity 'draft'. They are engineering scaffolding written
 * for the platform, not vendor-published data and not reviewed by this
 * operator's engineers — so they are not entitled to any higher rung on the
 * ladder until somebody signs for them.
 *
 *   npx tsx scripts/generate-twin-seed.ts > supabase/migrations/<ts>_seed_twin_library.sql
 */
import { miningAssetClassLibrary } from "../src/lib/asset-twins/mining-library";
import { miningOemModelOverlays } from "../src/lib/asset-twins/oem-overlays";
import { ballMillTemplate } from "../src/lib/asset-twins/ball-mill";
import { blastholeDrillTemplate } from "../src/lib/asset-twins/blasthole-drill";
import { centrifugalPumpTemplate } from "../src/lib/asset-twins/centrifugal-pump";
import { conveyorSystemTemplate } from "../src/lib/asset-twins/conveyor-system";
import { draglineTemplate } from "../src/lib/asset-twins/dragline";
import { electricMotorTemplate } from "../src/lib/asset-twins/electric-motor";
import { hydraulicMiningShovelTemplate } from "../src/lib/asset-twins/hydraulic-mining-shovel";
import { industrialGearboxTemplate } from "../src/lib/asset-twins/industrial-gearbox";
import { largeWheelLoaderTemplate } from "../src/lib/asset-twins/large-wheel-loader";
import { primaryCrusherTemplate } from "../src/lib/asset-twins/primary-crusher";
import { sagMillTemplate } from "../src/lib/asset-twins/sag-mill";
import { thickenerTemplate } from "../src/lib/asset-twins/thickener";
import { ultraClassHaulTruckTemplate } from "../src/lib/asset-twins/ultra-class-haul-truck";
import {
  validateAssetClassTemplate,
  type AssetClassTemplate,
} from "../src/lib/asset-twins";

const detailed: AssetClassTemplate[] = [
  ballMillTemplate,
  blastholeDrillTemplate,
  centrifugalPumpTemplate,
  conveyorSystemTemplate,
  draglineTemplate,
  electricMotorTemplate,
  hydraulicMiningShovelTemplate,
  industrialGearboxTemplate,
  largeWheelLoaderTemplate,
  primaryCrusherTemplate,
  sagMillTemplate,
  thickenerTemplate,
  ultraClassHaulTruckTemplate,
];

// Codes collide between the detailed templates and the mining-library starters
// (MIN-DRILL-BH, MIN-CRUSH-PRI, MIN-HAUL-TRUCK, MIN-DRAGLINE). The detailed one
// wins — a starter carries no components and would silently replace a populated
// template with an empty one if it were loaded second.
const byCode = new Map<string, AssetClassTemplate>();
for (const t of [...miningAssetClassLibrary, ...detailed]) {
  const existing = byCode.get(t.code);
  if (!existing || t.components.length > existing.components.length)
    byCode.set(t.code, t);
}
const templates = [...byCode.values()].sort((a, b) =>
  a.code.localeCompare(b.code),
);

// A template the library itself considers invalid must not reach the database.
const invalid = templates.flatMap((t) =>
  validateAssetClassTemplate(t).map((i) => `${t.code}: ${i.path} — ${i.message}`),
);
if (invalid.length > 0) {
  console.error("Refusing to emit — invalid templates:\n" + invalid.join("\n"));
  process.exit(1);
}

const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;
const json = (v: unknown) => `${lit(JSON.stringify(v))}::jsonb`;

const out: string[] = [
  "-- GENERATED by scripts/generate-twin-seed.ts — do not edit by hand.",
  "-- Source of truth: src/lib/asset-twins. Regenerate rather than patching.",
  "--",
  "-- Maturity is 'draft' for every row here. These templates are platform",
  "-- engineering scaffolding: they describe how a machine of this class is put",
  "-- together and how it fails, which is defensible general engineering, but no",
  "-- vendor published them and no engineer at this operator has reviewed them.",
  "-- Nothing may be promoted up the ladder by a migration.",
  "",
];

for (const t of templates) {
  out.push(
    `insert into asset_twin_templates (template_key, version, asset_family, asset_class, title, description, maturity, template, evidence)`,
    `values (${lit(t.code)}, ${lit(t.schemaVersion)}, ${lit(t.family)}, ${lit(t.name)}, ${lit(t.name)},`,
    `        ${lit(t.description)}, 'draft', ${json(t)}, '[]'::jsonb)`,
    `on conflict (template_key, version) do update set`,
    `  template = excluded.template, description = excluded.description,`,
    `  asset_family = excluded.asset_family, asset_class = excluded.asset_class,`,
    `  updated_at = now();`,
    "",
  );
}

for (const o of miningOemModelOverlays) {
  out.push(
    `insert into asset_twin_model_overlays (template_id, manufacturer, model, version, maturity, overlay, evidence)`,
    `select t.id, ${lit(o.manufacturer)}, ${lit(o.model)}, ${lit(o.schemaVersion)}, 'draft', ${json(o)}, '[]'::jsonb`,
    `from asset_twin_templates t where t.template_key = ${lit(o.assetClassCode)}`,
    `on conflict (template_id, manufacturer, model, version) do update set overlay = excluded.overlay;`,
    "",
  );
}

out.push(
  `-- ${templates.length} class template(s), ${miningOemModelOverlays.length} OEM overlay(s) from the code library.`,
  "notify pgrst, 'reload schema';",
  "",
);

process.stdout.write(out.join("\n"));
