// Requested identities are historical commercial scope, not a new runtime registry.
export const sourceCommit = "448cec478249cccda8e4a4a89666b13e8767b1cf";
export const portfolio = [
  [
    "preventive-maintenance",
    "Preventive Maintenance",
    "PreventiveMaintenanceAgent",
    ["maintenance_strategy", "asset_strategy"],
    "bounded-advisory",
    "C1.10",
  ],
  [
    "predictive-analytics",
    "Predictive Analytics",
    null,
    ["data_analytics"],
    "unverified",
    "C1.03",
  ],
  [
    "asset-health",
    "Asset Health",
    "AssetHealthAgent",
    ["condition_monitoring"],
    "bounded-advisory",
    "C1.06",
  ],
  [
    "work-order",
    "Work Order",
    "WorkOrderAgent",
    ["work_order_management"],
    "bounded-advisory",
    "C5",
  ],
  [
    "root-cause-analysis",
    "Root Cause Analysis",
    "RootCauseAnalysisAgent",
    ["fracas_rca"],
    "bounded-advisory",
    "C1.07",
  ],
  [
    "spare-parts",
    "Spare Parts",
    "InventoryAgent",
    ["inventory_management"],
    "bounded-advisory",
    "C1.08",
  ],
  [
    "performance-analysis",
    "Performance Analysis",
    null,
    ["data_analytics"],
    "unverified",
    null,
  ],
  [
    "failure-mode",
    "Failure Mode",
    null,
    ["reliability_engineering"],
    "partial",
    "C1.03",
  ],
  [
    "cost-optimization",
    "Cost Optimization",
    null,
    ["financial_contract"],
    "unverified",
    null,
  ],
  [
    "compliance",
    "Compliance",
    "HSEComplianceAgent",
    ["compliance_auditing"],
    "shared-dispatch",
    null,
  ],
  [
    "risk-assessment",
    "Risk Assessment",
    "RiskAssessmentAgent",
    ["sync-risk-analysis"],
    "bounded-advisory",
    "R6.15",
  ],
  ["energy-efficiency", "Energy Efficiency", null, [], "unverified", null],
  [
    "environmental",
    "Environmental",
    null,
    ["sustainability_esg"],
    "unverified",
    null,
  ],
  ["safety", "Safety", "HSEComplianceAgent", [], "shared-dispatch", "C1.11"],
  [
    "reliability",
    "Reliability",
    "ReliabilityAgent",
    ["reliability_engineering"],
    "partial",
    "C1.03",
  ],
  [
    "central-coordination",
    "Central Coordination & Human-in-the-Loop",
    "CentralCoordinationAgent",
    ["maintenance_operations"],
    "bounded-advisory",
    "C1.02",
  ],
].map(([id, name, dispatch, candidateKeys, sourceStatus, registerRef]) => ({
  id,
  name,
  dispatch,
  candidateKeys,
  sourceStatus,
  registerRef,
  microsoftStatus: "not-integrated",
  listingReady: false,
  distinctWorkflowVerified: false,
}));

// Full-platform SaaS remains the commercial product; agents are additional
// experiences. Bundle, pricing and approved entitlement policy remain undecided.
export const listingScope = {
  platform: {
    name: "SyncAI",
    scope: "complete-platform",
    offerType: "SaaS",
    existingWorkstream: 634,
    published: false,
  },
  agents: {
    requestedCount: 16,
    packageCountRequired: 16,
    scope: "additional-discoverable-experiences",
    publishedCount: 0,
  },
  commercialPolicy: { bundle: null, pricingModel: null, approved: false },
  marketplaceSearchResultCount: null,
};
