-- ============================================================================
-- A fixture that makes the claim-type guard fire.
--
-- Before this, every chunk in the corpus belonged to a class with standing on
-- failure behaviour, so the enforcement added in 20260825090000 could never
-- have excluded anything. A guard that has never refused is a guard nobody has
-- tested.
--
-- IMPORTANT: the prose below is SYNTHETIC. It is written here to imitate the
-- register of a manufacturer's sales brochure — confident durability language
-- with no measurement behind it — because that is precisely the failure mode
-- being defended against. No copyrighted OEM text appears in this repository,
-- which is public.
--
-- The chunk carries no embedding, so it participates in the text-search path
-- and not the vector path. That is deliberate: the guard must hold on both
-- routes, and leaving this one out of the vector index proves the text route
-- enforces on its own rather than inheriting protection from the other.
-- ============================================================================

-- WHERE THE ROW IS CREATED, AND WHY NO LONGER HERE.
--
-- This migration used to write the fixture at this point with no
-- organization_id, and it succeeded only because the corpus-scope trigger did
-- not exist yet. 20260825146000 then had to go back and scope it, and
-- audit_kb_corpus_scope() still describes the row as one that "predates the
-- trigger". Replaying the chain onto a database that already HAS that trigger
-- fails outright here — which is exactly what production did.
--
-- The statement could not be fixed in place: reliability_kb_chunks has no
-- organization_id column until 20260825140000, so a write here can be scoped
-- or it can run on a fresh database, never both. 20260825146000 already owns
-- making this fixture correctly scoped, and by then both the column and the
-- trigger exist, so the write belongs there and the row is created scoped
-- once rather than created wrong and repaired.
--
-- This migration is retained rather than deleted because it is already
-- recorded as applied everywhere, and because the reasoning above is the
-- point of it. The fixture content now lives in 20260825146000.
