import type { AssetClassTemplate, FailureModeTemplate } from "./types";

const draftFailure = (
  code: string,
  componentCode: string,
  name: string,
  mechanism: string,
  causes: string[],
  effects: string[],
  detectableBy: string[],
  verificationMethods: string[],
  severity: 1 | 2 | 3 | 4 | 5,
): FailureModeTemplate => ({
  code,
  componentCode,
  name,
  mechanism,
  causes,
  effects,
  detectableBy,
  verificationMethods,
  recommendedActions: [],
  severity,
  evidence: [],
  reviewState: "draft",
});

/** Manufacturer-neutral ball mill template. Approved OEM and site evidence is required for limits, intervals, and acceptance criteria. */
export const ballMillTemplate: AssetClassTemplate = {
  schemaVersion: "0.1.0",
  code: "PROC-BALL-MILL",
  name: "Ball mill",
  family: "fixed_material_processing",
  description:
    "Governed engineering foundation for manufacturer-neutral ball mills used in mineral-processing grinding circuits.",
  functions: [
    "receive_prepared_feed_and_process_water",
    "reduce_particle_size_with_grinding_media",
    "retain_and_cascade_ball_charge",
    "transmit_drive_torque",
    "support_rotating_shell",
    "discharge_ground_slurry",
    "control_lubrication_jacking_filtration_and_cooling",
  ],
  operatingStates: [
    "offline",
    "starting",
    "running_loaded",
    "running_low_load",
    "stopping",
    "inching",
    "maintenance_test",
  ],
  standards: ["ISO 55000", "ISO 13374", "ISO 23247"],
  reviewState: "draft",
  components: [
    {
      code: "BM-SHELL-LINER-MEDIA",
      name: "Mill shell, heads, liners, grinding media, and fasteners",
      functions: [
        "contain grinding media and slurry",
        "transfer cyclic grinding loads",
        "protect shell and heads",
        "support charge motion",
      ],
      telemetryConcepts: [
        "shell_vibration",
        "acoustic_level",
        "mill_load",
        "liner_wear",
        "bolt_condition",
        "media_charge_condition",
      ],
      inspectionZones: [
        "shell plates",
        "head plates",
        "liner rows",
        "lifters",
        "liner bolts",
        "grinding media",
        "feed and discharge heads",
      ],
      failureModes: [
        draftFailure(
          "BM-SHELL-LINER-MEDIA-DEGRADE",
          "BM-SHELL-LINER-MEDIA",
          "Shell, liner, media, or fastener degradation",
          "fatigue, abrasion, impact, and charge-motion change",
          [
            "cyclic loading",
            "abrasive slurry",
            "impact loading",
            "loose fasteners",
            "corrosion",
            "media degradation",
          ],
          [
            "loss of liner protection",
            "inefficient grinding",
            "shell or head damage",
            "abnormal vibration",
            "unplanned shutdown",
          ],
          [
            "acoustic_monitoring",
            "vibration",
            "rgb_visual_inspection",
            "drone_rgb",
            "inspection",
          ],
          [
            "internal_visual_inspection",
            "non_destructive_testing",
            "fastener_condition_check",
            "dimensional_wear_measurement",
            "media_condition_review",
          ],
          5,
        ),
      ],
    },
    {
      code: "BM-TRUNNION-BEARING",
      name: "Trunnions, main bearings, and bearing supports",
      functions: [
        "support rotating mill mass",
        "maintain alignment",
        "transmit radial and axial loads",
      ],
      telemetryConcepts: [
        "bearing_temperature",
        "bearing_vibration",
        "oil_pressure",
        "oil_flow",
        "trunnion_displacement",
      ],
      inspectionZones: [
        "feed trunnion",
        "discharge trunnion",
        "bearing pads or shells",
        "housings",
        "pedestals",
        "seals",
      ],
      failureModes: [
        draftFailure(
          "BM-BEARING-DEGRADE",
          "BM-TRUNNION-BEARING",
          "Trunnion or main-bearing degradation",
          "wear, contamination, or lubrication-related distress",
          [
            "lubrication loss",
            "contamination",
            "misalignment",
            "overload",
            "cooling loss",
          ],
          [
            "abnormal heat",
            "vibration",
            "loss of alignment",
            "bearing damage",
            "mill trip",
          ],
          [
            "temperature",
            "vibration",
            "oil_analysis",
            "drone_thermal",
            "inspection",
          ],
          [
            "bearing_clearance_or_lift_check",
            "oil_sample_confirmation",
            "alignment_survey",
            "qualified_engineering_inspection",
          ],
          5,
        ),
      ],
    },
    {
      code: "BM-DRIVE",
      name: "Motor, coupling, drive train, ring gear and pinion, or gearless drive",
      functions: [
        "generate torque",
        "transmit torque",
        "rotate mill",
        "support controlled inching or creeping",
        "accommodate geared or gearless drive applicability",
      ],
      telemetryConcepts: [
        "motor_current",
        "motor_power",
        "drive_vibration",
        "gear_mesh_frequency",
        "drive_temperature",
        "mill_speed",
        "torque",
      ],
      inspectionZones: [
        "motor",
        "coupling",
        "gearbox if fitted",
        "pinion",
        "ring gear",
        "gearless drive interfaces",
        "guards",
        "inching or creeping drive",
      ],
      failureModes: [
        draftFailure(
          "BM-DRIVE-DEGRADE",
          "BM-DRIVE",
          "Main-drive, gear-mesh, or gearless-drive degradation",
          "wear, misalignment, electrical degradation, or torque-transfer fault",
          [
            "lubrication loss",
            "misalignment",
            "tooth damage",
            "electrical fault",
            "overload",
            "foundation movement",
          ],
          [
            "torque loss",
            "abnormal vibration",
            "drive damage progression",
            "loss of mill availability",
          ],
          [
            "vibration",
            "motor_current",
            "thermal",
            "oil_analysis",
            "inspection",
            "fault_code",
          ],
          [
            "drive_alignment_survey",
            "gear_contact_inspection_if_geared",
            "electrical_test_if_gearless",
            "oil_sample_confirmation",
            "qualified_drive_review",
          ],
          5,
        ),
      ],
    },
    {
      code: "BM-LUBE-JACK-COOL",
      name: "Lubrication, jacking, filtration, and cooling systems",
      functions: [
        "deliver lubricant",
        "lift bearing surfaces during required states",
        "remove contaminants",
        "reject heat",
      ],
      telemetryConcepts: [
        "lubricant_pressure",
        "jacking_pressure",
        "lubricant_flow",
        "lubricant_temperature",
        "filter_differential_pressure",
        "lubricant_condition",
        "cooling_flow",
      ],
      inspectionZones: [
        "reservoirs",
        "pumps",
        "filters",
        "coolers",
        "distribution lines",
        "spray systems if fitted",
        "sample points",
      ],
      failureModes: [
        draftFailure(
          "BM-LUBE-JACK-COOL-LOSS",
          "BM-LUBE-JACK-COOL",
          "Lubrication, jacking, filtration, or cooling performance loss",
          "functional degradation from loss of delivery, contamination control, lift, or heat rejection",
          [
            "pump failure",
            "blocked line",
            "filter bypass",
            "cooler fouling",
            "leakage",
            "contamination",
          ],
          [
            "bearing or drive damage",
            "abnormal heat",
            "failed start or stop support",
            "secondary drivetrain failure",
          ],
          ["pressure", "flow", "temperature", "oil_analysis", "inspection"],
          [
            "lubrication_system_function_test",
            "jacking_system_function_test",
            "oil_sample_confirmation",
            "cooler_performance_check",
            "distribution_point_inspection",
          ],
          5,
        ),
      ],
    },
    {
      code: "BM-FEED-DISCHARGE",
      name: "Feed and discharge configuration",
      functions: [
        "admit feed and process water",
        "control discharge",
        "retain grinding media",
        "route slurry and oversize",
      ],
      telemetryConcepts: [
        "feed_rate",
        "feed_density",
        "discharge_flow",
        "discharge_density",
        "chute_blockage",
        "spillage",
        "classification_state",
      ],
      inspectionZones: [
        "feed chute",
        "feed spout",
        "discharge grate or overflow interface",
        "trunnion liner",
        "trommel or screen if fitted",
        "launders",
        "seals",
      ],
      failureModes: [
        draftFailure(
          "BM-FEED-DISCHARGE-DEGRADE",
          "BM-FEED-DISCHARGE",
          "Feed or discharge blockage, wear, or containment loss",
          "abrasion, blockage, media carryover, or flow-interface degradation",
          [
            "coarse or variable feed",
            "high wear",
            "poor flow",
            "seal deterioration",
            "screen or grate damage",
          ],
          [
            "reduced throughput",
            "spillage",
            "process instability",
            "media loss",
            "secondary equipment damage",
          ],
          [
            "fixed_camera",
            "rgb_visual_inspection",
            "flow",
            "density",
            "vibration",
            "inspection",
          ],
          [
            "isolated_internal_inspection",
            "wear_measurement",
            "flow_path_inspection",
            "process_review",
          ],
          4,
        ),
      ],
    },
    {
      code: "BM-CTRL-PROTECT",
      name: "Instrumentation, controls, interlocks, and protection",
      functions: [
        "measure operating condition",
        "control mill sequence",
        "protect equipment and personnel",
        "record events",
      ],
      telemetryConcepts: [
        "mill_speed",
        "mill_power",
        "bearing_temperature",
        "lubrication_status",
        "jacking_status",
        "vibration_trip_status",
        "fault_code",
        "communication_health",
      ],
      inspectionZones: [
        "sensors",
        "PLC and remote I/O",
        "drive controls",
        "interlocks",
        "protective devices",
        "networks",
      ],
      failureModes: [
        draftFailure(
          "BM-CTRL-PROTECT-FAULT",
          "BM-CTRL-PROTECT",
          "Control, instrumentation, or protective-function degradation",
          "functional failure",
          [
            "sensor drift",
            "wiring damage",
            "logic fault",
            "communication loss",
            "bypassed protection",
          ],
          [
            "incorrect operation",
            "missed protection",
            "nuisance trip",
            "unsafe or damaging sequence",
          ],
          ["fault_code", "signal_validation", "inspection", "functional_test"],
          [
            "instrument_calibration_check",
            "interlock_function_test",
            "logic_review",
            "independent_engineering_verification",
          ],
          5,
        ),
      ],
    },
  ],
};
