import type { AssetClassTemplate, FailureModeTemplate } from "./types";

const draftFailure = (
  code: string,
  componentCode: string,
  name: string,
  mechanism: string,
  detectableBy: string[],
  verificationMethods: string[],
  severity: 1 | 2 | 3 | 4 | 5,
): FailureModeTemplate => ({
  code,
  componentCode,
  name,
  mechanism,
  causes: [],
  effects: [],
  detectableBy,
  verificationMethods,
  recommendedActions: [],
  severity,
  evidence: [],
  reviewState: "draft",
});

export const blastholeDrillTemplate: AssetClassTemplate = {
  schemaVersion: "0.1.0",
  code: "MIN-DRILL-BH",
  name: "Blasthole drill",
  family: "mobile_mining_drilling",
  description: "Manufacturer-neutral engineering template for large rotary blasthole drills.",
  functions: ["position", "level", "raise_mast", "rotate", "feed", "flush", "change_pipe", "propel"],
  operatingStates: ["offline", "tramming", "leveling", "mast_raising", "drilling", "pipe_handling", "maintenance_test"],
  standards: ["ISO 55000", "ISO 13374", "ISO 23247"],
  reviewState: "draft",
  components: [
    {
      code: "BHD-MAST",
      name: "Mast and support structure",
      functions: ["support drill string", "maintain alignment", "transfer feed and torque loads"],
      telemetryConcepts: ["mast_angle", "mast_strain", "feed_force", "vibration", "cycle_count"],
      inspectionZones: ["mast chords", "welds", "pivot points", "raising cylinders", "guides"],
      failureModes: [draftFailure("BHD-MAST-CRACK", "BHD-MAST", "Mast fatigue cracking", "cyclic feed and vibration loading causes crack initiation and growth", ["drone_rgb", "drone_lidar", "inspection", "strain_trend"], ["magnetic_particle", "ultrasonic_test", "structural_engineering_assessment"], 5)],
    },
    {
      code: "BHD-ROTARY",
      name: "Rotary head and drive",
      functions: ["apply drill-string torque", "control rotation speed", "support axial drilling loads"],
      telemetryConcepts: ["rotation_speed", "rotation_torque", "motor_current", "gearcase_temperature", "bearing_temperature"],
      inspectionZones: ["rotary head", "gearcase", "motors", "bearings", "couplings"],
      failureModes: [draftFailure("BHD-ROTARY-BEARING", "BHD-ROTARY", "Rotary-head bearing degradation", "wear, contamination or lubrication loss increases friction and clearance", ["vibration", "temperature", "oil_analysis", "drone_thermal"], ["bearing_inspection", "oil_sample_confirmation", "alignment_check"], 5)],
    },
    {
      code: "BHD-FEED",
      name: "Feed and pulldown system",
      functions: ["apply controlled axial force", "raise and lower drill string", "hold commanded position"],
      telemetryConcepts: ["feed_force", "feed_speed", "feed_position", "hydraulic_pressure", "chain_or_cable_tension"],
      inspectionZones: ["feed cylinders", "chains or cables", "carriage", "sheaves", "guides"],
      failureModes: [draftFailure("BHD-FEED-WEAR", "BHD-FEED", "Feed-system wear or misalignment", "progressive wear or looseness changes load path and carriage alignment", ["inspection", "drone_rgb", "motion_tracking", "pressure_trend"], ["wear_measurement", "alignment_survey", "functional_test"], 4)],
    },
    {
      code: "BHD-AIR",
      name: "Compressed-air and flushing system",
      functions: ["remove cuttings", "cool the bit", "stabilize drilling process"],
      telemetryConcepts: ["air_pressure", "air_flow", "compressor_temperature", "compressor_power", "filter_differential_pressure"],
      inspectionZones: ["compressor", "coolers", "hoses", "receiver", "filters"],
      failureModes: [draftFailure("BHD-AIR-LOSS", "BHD-AIR", "Insufficient flushing air", "leakage, restriction or compressor degradation reduces delivered pressure or flow", ["pressure", "flow", "temperature", "inspection", "power_trend"], ["leak_test", "compressor_performance_test", "filter_inspection"], 4)],
    },
    {
      code: "BHD-LEVEL-PROPEL",
      name: "Leveling and propel system",
      functions: ["position drill", "stabilize machine", "maintain drilling geometry"],
      telemetryConcepts: ["level_angle", "jack_pressure", "propel_speed", "track_pressure", "machine_inclination"],
      inspectionZones: ["leveling jacks", "crawler frames", "track drives", "pins", "hoses"],
      failureModes: [draftFailure("BHD-LEVEL-LEAK", "BHD-LEVEL-PROPEL", "Leveling-system hydraulic leakage", "seal, hose or fitting damage permits fluid loss and support drift", ["inspection", "drone_rgb", "pressure_decay", "fluid_level"], ["pressure_hold_test", "leak_source_inspection", "functional_level_test"], 5)],
    },
    {
      code: "BHD-CONTROL",
      name: "Electrical controls and protection",
      functions: ["coordinate drilling", "protect personnel and equipment", "record faults"],
      telemetryConcepts: ["voltage", "current", "fault_code", "interlock_state", "communication_health", "cabinet_temperature"],
      inspectionZones: ["control cabinets", "sensors", "interlocks", "cables", "operator station"],
      failureModes: [draftFailure("BHD-CONTROL-INTERLOCK", "BHD-CONTROL", "Intermittent control or interlock fault", "sensor, wiring or logic degradation causes inconsistent protective-state detection", ["fault_code", "event_log", "inspection", "communication_health"], ["functional_interlock_test", "electrical_inspection", "logic_review"], 5)],
    },
  ],
};
