import type { AssetClassTemplate, FailureModeTemplate } from "./types";

const draftFailure = (
  code: string,
  componentCode: string,
  name: string,
  mechanism: string,
  causes: string[],
  effects: string[],
  detectableBy: string[],
  verificationMethods: string[],
  severity: 1 | 2 | 3 | 4 | 5,
): FailureModeTemplate => ({
  code,
  componentCode,
  name,
  mechanism,
  causes,
  effects,
  detectableBy,
  verificationMethods,
  recommendedActions: [],
  severity,
  evidence: [],
  reviewState: "draft",
});

export const conveyorSystemTemplate: AssetClassTemplate = {
  schemaVersion: "0.2.0",
  code: "FP-CONVEYOR-BELT",
  name: "Bulk material belt conveyor",
  family: "fixed_plant_material_handling",
  description: "Manufacturer-neutral engineering template for bulk material belt conveyor systems.",
  functions: ["receive_material", "transport_material", "discharge_material", "control_tension", "protect_personnel_and_equipment"],
  operatingStates: ["offline", "isolated", "starting", "running_empty", "running_loaded", "stopping", "tripped", "maintenance_test"],
  standards: ["ISO 55000", "ISO 13374", "ISO 23247"],
  reviewState: "draft",
  components: [
    {
      code: "CV-BELT",
      name: "Conveyor belt and splices",
      functions: ["carry material", "transmit tension", "maintain trough profile"],
      telemetryConcepts: ["belt_speed", "belt_tension", "belt_tracking", "splice_pass_count", "load_rate"],
      inspectionZones: ["carry cover", "return cover", "edges", "splices", "repair patches"],
      failureModes: [draftFailure("CV-BELT-DAMAGE", "CV-BELT", "Belt damage or splice deterioration", "wear, impact, fatigue or adhesion loss reduces belt integrity", ["material impact", "mis-tracking", "foreign object", "ageing", "poor splice condition"], ["material loss", "belt rupture", "unplanned shutdown"], ["fixed_camera", "drone_rgb", "inspection", "belt_edge_monitor", "splice_monitor"], ["deenergized_visual_inspection", "belt_thickness_measurement", "splice_assessment"], 5)],
    },
    {
      code: "CV-PULLEY",
      name: "Head, tail, bend and snub pulleys",
      functions: ["redirect belt", "transmit torque", "support tension"],
      telemetryConcepts: ["pulley_speed", "bearing_temperature", "vibration", "lagging_slip", "shaft_displacement"],
      inspectionZones: ["pulley shell", "lagging", "shaft", "bearings", "locking assemblies"],
      failureModes: [draftFailure("CV-PULLEY-BEARING", "CV-PULLEY", "Pulley bearing degradation", "surface distress, contamination or lubrication loss increases friction and clearance", ["contamination", "lubrication loss", "misalignment", "overload"], ["heat", "vibration", "shaft damage", "belt stoppage"], ["thermal", "vibration", "ultrasound", "inspection"], ["bearing_inspection", "lubricant_analysis", "alignment_check"], 5)],
    },
    {
      code: "CV-IDLER",
      name: "Carry and return idlers",
      functions: ["support belt", "maintain belt profile", "limit rolling resistance"],
      telemetryConcepts: ["idler_temperature", "idler_rotation", "belt_sag", "acoustic_emission"],
      inspectionZones: ["carry idlers", "return idlers", "impact beds", "training idlers"],
      failureModes: [draftFailure("CV-IDLER-SEIZE", "CV-IDLER", "Idler seizure or bearing failure", "bearing degradation prevents free rotation and generates heat", ["seal failure", "contamination", "lubrication loss", "impact"], ["belt damage", "fire risk", "energy loss", "material spillage"], ["drone_thermal", "thermal", "acoustic", "inspection"], ["deenergized_rotation_check", "bearing_inspection", "thermal_confirmation"], 4)],
    },
    {
      code: "CV-DRIVE",
      name: "Drive motor, coupling and gearbox",
      functions: ["generate torque", "control belt speed", "transmit power"],
      telemetryConcepts: ["motor_current", "motor_temperature", "gearbox_temperature", "vibration", "speed", "torque"],
      inspectionZones: ["motor", "coupling", "gearbox", "baseplate", "guards"],
      failureModes: [draftFailure("CV-DRIVE-DEGRADE", "CV-DRIVE", "Drive train degradation", "bearing, gear, coupling or alignment deterioration increases vibration and heat", ["misalignment", "lubrication loss", "overload", "foundation looseness"], ["reduced capacity", "drive trip", "secondary damage"], ["vibration", "thermal", "oil_analysis", "motor_current_signature"], ["alignment_check", "oil_sample_confirmation", "gearbox_inspection", "motor_test"], 5)],
    },
    {
      code: "CV-TAKEUP",
      name: "Take-up and tensioning system",
      functions: ["maintain belt tension", "accommodate belt stretch", "control traction"],
      telemetryConcepts: ["takeup_position", "takeup_force", "hydraulic_pressure", "counterweight_position", "belt_tension"],
      inspectionZones: ["take-up carriage", "rails", "ropes or cylinders", "counterweight", "sheaves"],
      failureModes: [draftFailure("CV-TAKEUP-FAULT", "CV-TAKEUP", "Take-up travel or force fault", "binding, leakage, rope damage or control failure prevents required tension control", ["corrosion", "misalignment", "hydraulic leakage", "rope wear", "obstruction"], ["belt slip", "mis-tracking", "excess sag", "belt damage"], ["position", "pressure", "drone_rgb", "inspection"], ["functional_travel_test", "rope_or_cylinder_inspection", "tension_verification"], 4)],
    },
    {
      code: "CV-TRANSFER",
      name: "Chutes, skirts and transfer points",
      functions: ["receive material", "control material trajectory", "contain dust and spillage"],
      telemetryConcepts: ["chute_level", "plug_switch", "dust_level", "material_flow", "liner_wear"],
      inspectionZones: ["feed chute", "discharge chute", "liners", "skirts", "impact zone"],
      failureModes: [draftFailure("CV-TRANSFER-BLOCK", "CV-TRANSFER", "Transfer blockage or containment failure", "material accumulation, wear or trajectory deviation restricts flow or releases material", ["wet material", "oversize", "liner failure", "poor trajectory", "skirt damage"], ["belt overload", "spillage", "dust release", "upstream trip"], ["level", "fixed_camera", "drone_rgb", "inspection", "flow_balance"], ["isolated_chute_inspection", "liner_measurement", "trajectory_assessment"], 4)],
    },
    {
      code: "CV-PROTECT",
      name: "Controls and protective devices",
      functions: ["detect unsafe conditions", "trip equipment", "support controlled starting and stopping"],
      telemetryConcepts: ["pull_cord_state", "belt_drift_state", "zero_speed_state", "sequence_permissive", "trip_code"],
      inspectionZones: ["pull cords", "drift switches", "speed switches", "guards", "control panels"],
      failureModes: [draftFailure("CV-PROTECT-FAULT", "CV-PROTECT", "Protective device or interlock fault", "sensor, wiring, configuration or actuator fault prevents intended protective response", ["sensor damage", "wiring fault", "bypass", "configuration error", "contamination"], ["unsafe operation", "failure to trip", "nuisance trip"], ["proof_test", "fault_code", "inspection", "state_mismatch"], ["approved_proof_test", "electrical_inspection", "configuration_review"], 5)],
    },
  ],
};
