import type { AssetClassTemplate, FailureModeTemplate } from "./types";

const draftFailure = (
  code: string,
  componentCode: string,
  name: string,
  mechanism: string,
  causes: string[],
  effects: string[],
  detectableBy: string[],
  verificationMethods: string[],
  severity: 1 | 2 | 3 | 4 | 5,
): FailureModeTemplate => ({
  code,
  componentCode,
  name,
  mechanism,
  causes,
  effects,
  detectableBy,
  verificationMethods,
  recommendedActions: [],
  severity,
  evidence: [],
  reviewState: "draft",
});

/** Manufacturer-neutral dragline template. OEM and site evidence is required for limits, intervals, and acceptance criteria. */
export const draglineTemplate: AssetClassTemplate = {
  schemaVersion: "0.1.0",
  code: "MIN-DRAGLINE",
  name: "Mining dragline",
  family: "mobile_mining_excavation",
  description:
    "Governed component, failure, telemetry, and inspection foundation for large walking draglines used in overburden removal and bulk excavation.",
  functions: [
    "excavate",
    "drag_bucket",
    "hoist_bucket",
    "swing_load",
    "dump_material",
    "walk_machine",
    "support_boom_and_machinery",
    "control_electrical_power",
  ],
  operatingStates: [
    "offline",
    "idle",
    "digging",
    "hoisting",
    "swinging_loaded",
    "dumping",
    "returning_empty",
    "walking",
    "maintenance_test",
  ],
  standards: ["ISO 55000", "ISO 13374", "ISO 23247"],
  reviewState: "draft",
  components: [
    {
      code: "DL-STRUCT",
      name: "Tub, revolving frame, mast, and boom structure",
      functions: ["support machine loads", "maintain geometry", "transfer digging, swing, and walking loads"],
      telemetryConcepts: ["structural_strain", "cycle_count", "shock_load", "boom_angle", "swing_load"],
      inspectionZones: ["tub", "revolving frame", "mast", "boom chords", "boom foot", "gantry", "counterweight supports"],
      failureModes: [
        draftFailure(
          "DL-STRUCT-FATIGUE",
          "DL-STRUCT",
          "Structural fatigue cracking or distortion",
          "fatigue",
          ["cyclic loading", "stress concentration", "impact", "corrosion", "geometry deviation"],
          ["reduced structural capacity", "load-path redistribution", "boom or frame instability"],
          ["drone_rgb", "drone_thermal", "drone_lidar", "strain_monitoring", "inspection"],
          ["non_destructive_testing", "dimensional_survey", "structural_engineering_assessment"],
          5,
        ),
      ],
    },
    {
      code: "DL-HOIST-DRAG",
      name: "Hoist and drag machinery",
      functions: ["apply hoist force", "apply drag force", "control bucket motion", "hold commanded loads"],
      telemetryConcepts: ["motor_current", "drum_speed", "gearbox_vibration", "bearing_temperature", "brake_status", "rope_load"],
      inspectionZones: ["hoist drums", "drag drums", "gear trains", "bearings", "couplings", "brakes", "machinery deck"],
      failureModes: [
        draftFailure(
          "DL-HOIST-DRIVE-DEGRADE",
          "DL-HOIST-DRAG",
          "Hoist or drag drivetrain degradation",
          "wear",
          ["lubrication loss", "contamination", "misalignment", "overload", "brake drag"],
          ["loss of torque", "abnormal heat", "vibration", "uncontrolled or unavailable motion"],
          ["vibration", "oil_analysis", "thermal", "motor_current", "inspection"],
          ["drivetrain_inspection", "oil_sample_confirmation", "backlash_or_clearance_check", "brake_function_test"],
          5,
        ),
      ],
    },
    {
      code: "DL-ROPE-SHEAVE",
      name: "Hoist, drag, dump ropes and sheaves",
      functions: ["transmit tensile load", "guide rope paths", "control bucket orientation", "support reeving geometry"],
      telemetryConcepts: ["rope_load", "rope_speed", "rope_cycles", "sheave_bearing_temperature", "rope_condition"],
      inspectionZones: ["hoist ropes", "drag ropes", "dump ropes", "boom point sheaves", "fairleads", "rope anchors", "equalizers"],
      failureModes: [
        draftFailure(
          "DL-ROPE-DEGRADE",
          "DL-ROPE-SHEAVE",
          "Wire-rope degradation or sheave-system damage",
          "fatigue",
          ["bending cycles", "abrasion", "corrosion", "poor spooling", "shock loading", "sheave misalignment"],
          ["loss of rope capacity", "bucket-control loss", "secondary structural or machinery damage"],
          ["rgb_visual_inspection", "drone_rgb", "magnetic_rope_testing", "rope_load", "inspection"],
          ["qualified_rope_inspection", "magnetic_rope_test", "diameter_and_broken_wire_measurement", "sheave_geometry_check"],
          5,
        ),
      ],
    },
    {
      code: "DL-SWING",
      name: "Swing drives, rollers, and rotating interface",
      functions: ["rotate upper structure", "support rotating mass", "control acceleration and braking", "maintain alignment"],
      telemetryConcepts: ["swing_speed", "motor_current", "gearcase_temperature", "bearing_vibration", "roller_load", "swing_position"],
      inspectionZones: ["swing motors", "gearboxes", "pinions", "rack or gear interface", "rollers", "rail", "center journal"],
      failureModes: [
        draftFailure(
          "DL-SWING-DEGRADE",
          "DL-SWING",
          "Swing drive or support-system degradation",
          "wear",
          ["lubrication loss", "uneven loading", "misalignment", "contamination", "gear damage"],
          ["abnormal vibration", "poor swing control", "load concentration", "loss of swing availability"],
          ["vibration", "thermal", "oil_analysis", "motor_current", "inspection"],
          ["gear_contact_inspection", "roller_load_or_clearance_check", "alignment_survey", "oil_sample_confirmation"],
          5,
        ),
      ],
    },
    {
      code: "DL-WALK",
      name: "Walking mechanism and ground interface",
      functions: ["lift and translate machine", "support static loads", "control walking sequence", "transfer loads to ground"],
      telemetryConcepts: ["walking_cycle_count", "cam_or_eccentric_position", "drive_current", "bearing_temperature", "shoe_load", "ground_inclination"],
      inspectionZones: ["walking shoes", "cams or eccentrics", "walking beams", "drive machinery", "pins", "bushings", "tub underside"],
      failureModes: [
        draftFailure(
          "DL-WALK-DEGRADE",
          "DL-WALK",
          "Walking mechanism wear, cracking, or synchronization loss",
          "wear",
          ["high ground reaction", "poor ground preparation", "lubrication loss", "misalignment", "cyclic fatigue"],
          ["restricted walking", "uneven tub loading", "structural overload", "loss of mobility"],
          ["drone_rgb", "drone_thermal", "position_monitoring", "motor_current", "inspection"],
          ["dimensional_inspection", "non_destructive_testing", "sequence_function_test", "ground_condition_assessment"],
          5,
        ),
      ],
    },
    {
      code: "DL-ELEC-CTRL",
      name: "Electrical drives, distribution, controls, and protection",
      functions: ["distribute electrical power", "control machine motions", "protect personnel and equipment", "record operating events"],
      telemetryConcepts: ["voltage", "current", "power_quality", "insulation_status", "cabinet_temperature", "fault_code", "communication_health"],
      inspectionZones: ["incoming power", "transformers", "switchgear", "drive cabinets", "motors", "terminations", "control networks", "protective devices"],
      failureModes: [
        draftFailure(
          "DL-ELEC-DEGRADE",
          "DL-ELEC-CTRL",
          "Electrical insulation, connection, drive, or control degradation",
          "thermal degradation",
          ["contamination", "loose connections", "cooling loss", "insulation aging", "power-quality disturbance"],
          ["thermal damage", "arc fault", "nuisance trip", "loss of motion or protection"],
          ["thermal", "current_imbalance", "insulation_monitoring", "fault_code", "inspection"],
          ["deenergized_electrical_inspection", "insulation_test", "connection_resistance_test", "protection_function_test"],
          5,
        ),
      ],
    },
    {
      code: "DL-LUBE",
      name: "Lubrication and support systems",
      functions: ["deliver lubricant", "control contamination", "remove heat", "support bearings, gears, ropes, and joints"],
      telemetryConcepts: ["lubricant_pressure", "lubricant_flow", "lubricant_temperature", "filter_differential_pressure", "lubricant_condition"],
      inspectionZones: ["reservoirs", "pumps", "filters", "distribution lines", "injectors", "coolers", "sample points"],
      failureModes: [
        draftFailure(
          "DL-LUBE-LOSS",
          "DL-LUBE",
          "Lubrication delivery loss or contamination",
          "wear",
          ["pump failure", "blocked line", "leakage", "wrong lubricant", "filter bypass", "water or particle ingress"],
          ["accelerated gear and bearing wear", "heat generation", "secondary drivetrain failure"],
          ["pressure", "flow", "temperature", "oil_analysis", "inspection"],
          ["lubrication_system_function_test", "oil_sample_confirmation", "distribution_point_inspection"],
          5,
        ),
      ],
    },
  ],
};
