import type { AssetClassTemplate, FailureModeTemplate } from "./types";

const failure = (code: string, componentCode: string, name: string, mechanism: string, causes: string[], effects: string[], detectableBy: string[], verificationMethods: string[], severity: 1|2|3|4|5): FailureModeTemplate => ({ code, componentCode, name, mechanism, causes, effects, detectableBy, verificationMethods, recommendedActions: [], severity, evidence: [], reviewState: "draft" });

export const industrialGearboxTemplate: AssetClassTemplate = {
  schemaVersion: "0.1.0",
  code: "ROT-GEARBOX",
  name: "Industrial gearbox",
  family: "rotating_equipment_power_transmission",
  description: "Manufacturer-neutral blueprint for parallel-shaft, helical, bevel and planetary industrial gearboxes.",
  functions: ["transmit_power", "change_speed", "change_torque", "support_rotating_elements", "contain_lubricant"],
  operatingStates: ["offline", "standby", "starting", "running", "stopping", "maintenance_test"],
  standards: ["ISO 55000", "ISO 13374", "ISO 20816"],
  reviewState: "draft",
  components: [
    { code: "GB-GEARS", name: "Gear mesh and tooth system", functions: ["transmit torque", "maintain ratio"], telemetryConcepts: ["gear_mesh_vibration", "load", "speed", "oil_debris"], inspectionZones: ["gear teeth", "mesh contact", "inspection ports"], failureModes: [failure("GB-GEARS-DAMAGE", "GB-GEARS", "Gear tooth surface or root damage", "fatigue, wear or overload damages tooth surfaces or roots", ["overload", "misalignment", "contamination", "lubrication deficiency"], ["noise", "vibration", "loss of torque transmission", "secondary damage"], ["vibration", "oil_analysis", "inspection", "acoustic"], ["borescope_inspection", "gear_contact_assessment", "oil_sample_confirmation"], 5)] },
    { code: "GB-BEARINGS", name: "Shafts and bearings", functions: ["support shafts", "maintain alignment"], telemetryConcepts: ["bearing_vibration", "bearing_temperature", "shaft_speed", "axial_position"], inspectionZones: ["bearing housings", "shaft ends", "coupling interfaces"], failureModes: [failure("GB-BEARING-DEGRADE", "GB-BEARINGS", "Bearing degradation", "surface distress, clearance change or lubrication failure degrades support", ["contamination", "misalignment", "overload", "lubrication loss"], ["heat", "vibration", "shaft movement", "gear damage"], ["vibration", "temperature", "oil_analysis", "ultrasound"], ["bearing_inspection", "alignment_check", "oil_sample_confirmation"], 5)] },
    { code: "GB-LUBE", name: "Lubrication and filtration", functions: ["deliver lubricant", "remove heat", "control contamination"], telemetryConcepts: ["oil_pressure", "oil_temperature", "oil_level", "filter_differential_pressure", "particle_count"], inspectionZones: ["reservoir", "pumps", "filters", "coolers", "lines"], failureModes: [failure("GB-LUBE-LOSS", "GB-LUBE", "Lubrication delivery deficiency", "lubricant quantity, quality or delivery is inadequate", ["low level", "pump fault", "blocked filter", "leak", "cooler restriction"], ["accelerated wear", "overheating", "gear and bearing damage"], ["pressure", "temperature", "oil_analysis", "inspection"], ["lubrication_system_test", "filter_inspection", "oil_sample_confirmation"], 5)] },
    { code: "GB-HOUSING", name: "Housing, seals and breathers", functions: ["contain lubricant", "maintain alignment", "exclude contamination"], telemetryConcepts: ["case_temperature", "oil_level", "internal_pressure"], inspectionZones: ["housing", "split lines", "seals", "breathers", "mounting feet"], failureModes: [failure("GB-SEAL-LEAK", "GB-HOUSING", "Seal or housing leakage", "seal deterioration, pressure or joint defects allow lubricant escape or contaminant ingress", ["seal wear", "blocked breather", "shaft movement", "joint looseness"], ["oil loss", "contamination", "environmental release"], ["inspection", "oil_level", "thermal"], ["leak_source_inspection", "breather_check", "shaft_runout_check"], 3)] },
    { code: "GB-MOUNT", name: "Foundation, mounts and alignment", functions: ["support gearbox", "preserve alignment", "transmit reaction loads"], telemetryConcepts: ["case_vibration", "alignment_state", "fastener_condition"], inspectionZones: ["baseplate", "mounting feet", "hold-down bolts", "couplings"], failureModes: [failure("GB-MOUNT-LOOSE", "GB-MOUNT", "Mounting looseness or misalignment", "foundation movement, looseness or distortion changes alignment", ["loose fasteners", "soft foot", "foundation degradation", "thermal growth mismatch"], ["elevated vibration", "coupling wear", "bearing and gear load concentration"], ["vibration", "inspection", "alignment"], ["laser_alignment", "soft_foot_check", "fastener_inspection"], 4)] },
  ],
};
