import type { AssetClassTemplate, FailureModeTemplate } from "./types";

const draftFailure = (
  code: string,
  componentCode: string,
  name: string,
  mechanism: string,
  detectableBy: string[],
  verificationMethods: string[],
): FailureModeTemplate => ({
  code,
  componentCode,
  name,
  mechanism,
  causes: [],
  effects: [],
  detectableBy,
  verificationMethods,
  recommendedActions: [],
  severity: 3,
  evidence: [],
  reviewState: "draft",
});

export const electricRopeShovelTemplate: AssetClassTemplate = {
  schemaVersion: "0.1.0",
  code: "MIN-LOAD-ERS",
  name: "Electric rope shovel",
  family: "mobile_mining_loading",
  description:
    "Reusable functional, component, failure and observation template for large electric rope shovels.",
  functions: ["dig", "crowd", "hoist", "swing", "dump", "propel", "brake", "lubricate", "cool"],
  operatingStates: [
    "offline",
    "idle",
    "digging",
    "hoisting",
    "swinging_loaded",
    "dumping",
    "swinging_empty",
    "propelling",
    "maintenance_test",
  ],
  standards: ["ISO 55000", "ISO 13374", "ISO 23247"],
  reviewState: "draft",
  components: [
    {
      code: "ERS-STRUCT",
      name: "Structural system",
      functions: ["support operating loads", "maintain geometry", "protect machinery"],
      telemetryConcepts: ["structural_vibration", "boom_deflection", "cycle_count", "payload"],
      inspectionZones: ["boom chords", "boom foot", "gantry", "machinery house", "carbody"],
      failureModes: [
        draftFailure(
          "ERS-STRUCT-CRACK",
          "ERS-STRUCT",
          "Structural crack",
          "fatigue crack initiation and propagation",
          ["drone_rgb", "drone_thermal", "drone_lidar", "optical_vibration", "inspection"],
          ["magnetic_particle", "phased_array_ultrasonic", "engineer_visual"],
        ),
        draftFailure(
          "ERS-STRUCT-DEFORM",
          "ERS-STRUCT",
          "Permanent deformation",
          "overload, impact or progressive stiffness loss",
          ["drone_lidar", "photogrammetry", "optical_deflection"],
          ["dimensional_survey", "structural_engineering_assessment"],
        ),
      ],
    },
    {
      code: "ERS-HOIST",
      name: "Hoist system",
      functions: ["raise and lower dipper", "control suspended load", "hold commanded position"],
      telemetryConcepts: ["hoist_current", "hoist_speed", "brake_temperature", "bearing_temperature"],
      inspectionZones: ["hoist motors", "drums", "brakes", "ropes", "sheaves"],
      failureModes: [
        draftFailure(
          "ERS-HOIST-BRAKE-DRAG",
          "ERS-HOIST",
          "Brake drag",
          "incomplete release, misalignment or friction",
          ["drone_thermal", "motor_current", "cycle_energy"],
          ["brake_clearance_inspection", "release_system_test"],
        ),
        draftFailure(
          "ERS-HOIST-ROPE-DAMAGE",
          "ERS-HOIST",
          "Visible rope deterioration",
          "wire breakage, corrosion, abrasion or bird-caging",
          ["drone_rgb", "zoom_video", "rope_tracking"],
          ["qualified_rope_inspection", "magnetic_rope_test"],
        ),
      ],
    },
    {
      code: "ERS-CROWD",
      name: "Crowd system",
      functions: ["position dipper in bank", "control penetration and retraction"],
      telemetryConcepts: ["crowd_current", "crowd_speed", "crowd_position", "bearing_temperature"],
      inspectionZones: ["crowd machinery", "handle", "rack and pinion", "saddles"],
      failureModes: [
        draftFailure(
          "ERS-CROWD-MISALIGN",
          "ERS-CROWD",
          "Crowd alignment deterioration",
          "wear, looseness or structural displacement",
          ["drone_rgb", "drone_lidar", "motion_trajectory", "temperature_asymmetry"],
          ["alignment_survey", "wear_measurement"],
        ),
      ],
    },
    {
      code: "ERS-SWING",
      name: "Swing system",
      functions: ["rotate upper works", "stop and hold rotation"],
      telemetryConcepts: ["swing_current", "swing_speed", "swing_acceleration", "gearcase_temperature"],
      inspectionZones: ["swing motors", "gearcases", "swing rack", "pinions", "brakes"],
      failureModes: [
        draftFailure(
          "ERS-SWING-ABNORMAL-HEAT",
          "ERS-SWING",
          "Abnormal swing-drive heating",
          "friction, overload, lubrication loss or misalignment",
          ["drone_thermal", "current_signature", "cycle_time"],
          ["vibration_analysis", "oil_analysis", "gear_inspection"],
        ),
      ],
    },
    {
      code: "ERS-ELEC",
      name: "Electrical power and controls",
      functions: ["distribute power", "control motion", "protect personnel and equipment"],
      telemetryConcepts: ["voltage", "current", "power_factor", "cabinet_temperature", "fault_code"],
      inspectionZones: ["trailing cable", "terminations", "motors", "electrical cabinets", "ventilation"],
      failureModes: [
        draftFailure(
          "ERS-ELEC-HOT-CONNECTION",
          "ERS-ELEC",
          "High-resistance electrical connection",
          "loose, contaminated, corroded or damaged connection",
          ["drone_thermal", "uv_corona", "current_imbalance"],
          ["deenergized_torque_check", "insulation_test", "electrical_inspection"],
        ),
      ],
    },
    {
      code: "ERS-LUBE",
      name: "Lubrication system",
      functions: ["deliver lubricant", "remove frictional heat", "exclude contamination"],
      telemetryConcepts: ["lubricant_pressure", "lubricant_flow", "reservoir_level", "component_temperature"],
      inspectionZones: ["reservoir", "pumps", "distribution blocks", "lines", "lubrication points"],
      failureModes: [
        draftFailure(
          "ERS-LUBE-STARVATION",
          "ERS-LUBE",
          "Lubrication starvation",
          "blocked line, failed pump, empty reservoir or incorrect delivery",
          ["drone_rgb", "drone_thermal", "pressure", "flow", "grease_purge_presence"],
          ["manual_lubrication_test", "line_inspection", "sample_analysis"],
        ),
      ],
    },
  ],
};

const starter = (
  code: string,
  name: string,
  family: string,
  functions: string[],
): AssetClassTemplate => ({
  schemaVersion: "0.1.0",
  code,
  name,
  family,
  description: `Starter asset-class shell for ${name}. Engineering content requires evidence ingestion and review.`,
  functions,
  operatingStates: ["offline", "idle", "operating", "degraded", "maintenance_test"],
  components: [],
  standards: ["ISO 55000", "ISO 13374", "ISO 23247"],
  reviewState: "draft",
});

export const miningAssetClassLibrary: AssetClassTemplate[] = [
  electricRopeShovelTemplate,
  starter("MIN-LOAD-HMS", "Hydraulic mining shovel", "mobile_mining_loading", ["dig", "swing", "dump", "propel"]),
  starter("MIN-HAUL-TRUCK", "Ultra-class haul truck", "mobile_mining_haulage", ["load", "haul", "dump", "retard", "steer"]),
  starter("MIN-LOAD-WL", "Large wheel loader", "mobile_mining_loading", ["dig", "lift", "carry", "dump", "steer"]),
  starter("MIN-DRILL-BH", "Blasthole drill", "mobile_mining_drilling", ["position", "level", "drill", "flush", "change_pipe"]),
  starter("MIN-CRUSH-PRI", "Primary crusher", "fixed_material_processing", ["receive", "size_reduce", "discharge", "protect"]),
  starter("MIN-CONV", "Mine conveyor system", "fixed_material_handling", ["transport", "track", "tension", "protect"]),
  starter("MIN-DRAGLINE", "Dragline", "mobile_mining_loading", ["drag", "hoist", "swing", "dump", "walk"]),
  starter("MIN-DOZER", "Large mining dozer", "mobile_mining_support", ["push", "rip", "grade", "steer"]),
  starter("MIN-GRADER", "Motor grader", "mobile_mining_support", ["grade", "scarify", "steer", "travel"]),
  starter("MIN-MOBILE-CRUSH", "Mobile crusher", "mobile_material_processing", ["receive", "size_reduce", "convey", "propel"]),
  starter("MIN-STACK-RECLAIM", "Stacker-reclaimer", "fixed_material_handling", ["stack", "reclaim", "slew", "luff", "travel"]),
];
