import type { AssetClassTemplate, FailureModeTemplate } from "./types";

const failure = (
  code: string,
  componentCode: string,
  name: string,
  mechanism: string,
  detectableBy: string[],
  verificationMethods: string[],
  severity: 1 | 2 | 3 | 4 | 5,
): FailureModeTemplate => ({
  code,
  componentCode,
  name,
  mechanism,
  causes: [],
  effects: [],
  detectableBy,
  verificationMethods,
  recommendedActions: [],
  severity,
  evidence: [],
  reviewState: "draft",
});

export const primaryCrusherTemplate: AssetClassTemplate = {
  schemaVersion: "0.2.0",
  code: "MIN-CRUSH-PRI",
  name: "Primary crusher",
  family: "fixed_material_processing",
  description: "Manufacturer-neutral engineering template for large gyratory or jaw primary crushing systems.",
  functions: ["receive", "size_reduce", "discharge", "protect", "lubricate", "control"],
  operatingStates: ["offline", "idle", "starting", "crushing", "blocked", "clearing", "maintenance_test"],
  standards: ["ISO 55000", "ISO 13374", "ISO 23247"],
  reviewState: "draft",
  components: [
    {
      code: "PCR-STRUCT",
      name: "Main frame and supporting structure",
      functions: ["support crushing loads", "maintain alignment", "contain material"],
      telemetryConcepts: ["frame_vibration", "structural_strain", "throughput", "crusher_state"],
      inspectionZones: ["main frame", "foundation interfaces", "shell", "access platforms"],
      failureModes: [failure("PCR-STRUCT-CRACK", "PCR-STRUCT", "Structural fatigue crack", "cyclic impact and crushing loads initiate and propagate cracking", ["inspection", "drone_rgb", "drone_lidar", "strain_trend"], ["magnetic_particle", "ultrasonic_test", "structural_engineering_assessment"], 5)],
    },
    {
      code: "PCR-CRUSH",
      name: "Crushing chamber and wear parts",
      functions: ["fracture feed material", "control product size", "resist abrasion"],
      telemetryConcepts: ["closed_side_setting", "power_draw", "throughput", "chamber_level", "product_size"],
      inspectionZones: ["mantle or jaw", "concaves or liners", "spider", "feed opening"],
      failureModes: [failure("PCR-CRUSH-WEAR", "PCR-CRUSH", "Excessive or uneven wear", "abrasion and impact progressively change chamber geometry", ["inspection", "laser_scan", "power_draw", "product_size"], ["dimensional_survey", "liner_profile_measurement", "engineer_visual"], 4)],
    },
    {
      code: "PCR-DRIVE",
      name: "Drive, eccentric and bearings",
      functions: ["transmit power", "generate crushing motion", "support rotating loads"],
      telemetryConcepts: ["motor_current", "bearing_temperature", "vibration", "speed", "oil_debris"],
      inspectionZones: ["motor", "coupling", "countershaft", "eccentric", "main bearings"],
      failureModes: [failure("PCR-DRIVE-BEARING-DEGRADE", "PCR-DRIVE", "Bearing degradation", "surface distress, contamination or lubrication loss increases friction and clearance", ["vibration", "temperature", "oil_analysis", "motor_current"], ["bearing_inspection", "oil_sample_confirmation", "alignment_check"], 5)],
    },
    {
      code: "PCR-LUBE-HYD",
      name: "Lubrication and hydraulic systems",
      functions: ["lubricate bearings", "remove heat", "support adjustment and protection functions"],
      telemetryConcepts: ["lubricant_pressure", "lubricant_flow", "oil_temperature", "filter_differential_pressure", "hydraulic_pressure"],
      inspectionZones: ["reservoir", "pumps", "filters", "coolers", "lines", "hydraulic power unit"],
      failureModes: [failure("PCR-LUBE-LOSS", "PCR-LUBE-HYD", "Lubrication delivery loss", "pump, restriction, leakage or low inventory prevents adequate lubricant delivery", ["pressure", "flow", "temperature", "inspection"], ["manual_flow_test", "filter_inspection", "oil_analysis"], 5)],
    },
    {
      code: "PCR-FEED-DISCH",
      name: "Feed and discharge interfaces",
      functions: ["control incoming material", "prevent blockages", "transfer crushed product"],
      telemetryConcepts: ["feed_rate", "chamber_level", "discharge_flow", "blockage_state", "belt_load"],
      inspectionZones: ["dump pocket", "rock breaker interface", "feed chute", "discharge chute"],
      failureModes: [failure("PCR-FEED-BLOCKAGE", "PCR-FEED-DISCH", "Persistent blockage or bridging", "oversize, geometry, moisture or flow instability interrupts material movement", ["camera", "level", "throughput", "operator_observation"], ["controlled_visual_inspection", "material_flow_assessment"], 4)],
    },
    {
      code: "PCR-ELEC-CTRL",
      name: "Electrical controls and protection",
      functions: ["control operation", "protect equipment", "record faults", "coordinate interlocks"],
      telemetryConcepts: ["voltage", "current", "fault_code", "interlock_state", "communication_health"],
      inspectionZones: ["motor control centre", "local panels", "sensors", "protection devices"],
      failureModes: [failure("PCR-CTRL-INTERLOCK", "PCR-ELEC-CTRL", "Interlock or protection fault", "sensor, logic, communication or actuator fault compromises protective coordination", ["fault_code", "interlock_state", "functional_test"], ["approved_protective_function_test", "electrical_inspection"], 5)],
    },
  ],
};
