import type { AssetClassTemplate, FailureModeTemplate } from "./types";

const draftFailure = (
  code: string,
  componentCode: string,
  name: string,
  mechanism: string,
  causes: string[],
  effects: string[],
  detectableBy: string[],
  verificationMethods: string[],
  severity: 1 | 2 | 3 | 4 | 5,
): FailureModeTemplate => ({
  code,
  componentCode,
  name,
  mechanism,
  causes,
  effects,
  detectableBy,
  verificationMethods,
  recommendedActions: [],
  severity,
  evidence: [],
  reviewState: "draft",
});

/** Manufacturer-neutral SAG mill template. Approved OEM and site evidence is required for limits, intervals, and acceptance criteria. */
export const sagMillTemplate: AssetClassTemplate = {
  schemaVersion: "0.1.0",
  code: "PROC-SAG-MILL",
  name: "Semi-autogenous grinding mill",
  family: "fixed_material_processing",
  description:
    "Governed engineering foundation for large semi-autogenous grinding mills used in mineral-processing comminution circuits.",
  functions: [
    "receive_ore_and_process_water",
    "reduce_particle_size",
    "retain_and_cascade_grinding_charge",
    "transmit_drive_torque",
    "support_rotating_shell",
    "discharge_ground_slurry",
    "control_lubrication_and_cooling",
  ],
  operatingStates: [
    "offline",
    "starting",
    "running_loaded",
    "running_low_load",
    "stopping",
    "inching",
    "maintenance_test",
  ],
  standards: ["ISO 55000", "ISO 13374", "ISO 23247"],
  reviewState: "draft",
  components: [
    {
      code: "SAG-SHELL-LINER",
      name: "Mill shell, heads, liners, and fasteners",
      functions: ["contain grinding charge", "transfer cyclic loads", "protect pressure boundary and shell"],
      telemetryConcepts: ["shell_vibration", "acoustic_level", "mill_load", "liner_wear", "bolt_condition"],
      inspectionZones: ["shell plates", "head plates", "liner rows", "lifters", "liner bolts", "feed and discharge heads"],
      failureModes: [
        draftFailure(
          "SAG-SHELL-LINER-DEGRADE",
          "SAG-SHELL-LINER",
          "Shell, liner, lifter, or fastener degradation",
          "fatigue and wear",
          ["cyclic loading", "abrasion", "impact", "loose fasteners", "corrosion"],
          ["loss of liner protection", "charge-motion change", "shell damage", "unplanned shutdown"],
          ["acoustic_monitoring", "vibration", "rgb_visual_inspection", "drone_rgb", "inspection"],
          ["internal_visual_inspection", "non_destructive_testing", "fastener_condition_check", "dimensional_wear_measurement"],
          5,
        ),
      ],
    },
    {
      code: "SAG-TRUNNION-BEARING",
      name: "Trunnions, main bearings, and bearing supports",
      functions: ["support rotating mill mass", "maintain alignment", "transmit radial and axial loads"],
      telemetryConcepts: ["bearing_temperature", "bearing_vibration", "oil_pressure", "oil_flow", "trunnion_displacement"],
      inspectionZones: ["feed trunnion", "discharge trunnion", "bearing pads or shells", "housings", "pedestals", "seals"],
      failureModes: [
        draftFailure(
          "SAG-BEARING-DEGRADE",
          "SAG-TRUNNION-BEARING",
          "Trunnion or main-bearing degradation",
          "wear",
          ["lubrication loss", "contamination", "misalignment", "overload", "cooling loss"],
          ["abnormal heat", "vibration", "loss of alignment", "bearing damage"],
          ["temperature", "vibration", "oil_analysis", "drone_thermal", "inspection"],
          ["bearing_clearance_or_lift_check", "oil_sample_confirmation", "alignment_survey", "qualified_engineering_inspection"],
          5,
        ),
      ],
    },
    {
      code: "SAG-DRIVE",
      name: "Motor, coupling, pinion, ring gear, and inching drive",
      functions: ["generate torque", "transmit torque", "rotate mill", "support controlled inching"],
      telemetryConcepts: ["motor_current", "motor_power", "pinion_vibration", "gear_mesh_frequency", "gear_temperature", "mill_speed"],
      inspectionZones: ["motor", "coupling", "gearbox if fitted", "pinion", "ring gear", "guards", "inching drive"],
      failureModes: [
        draftFailure(
          "SAG-DRIVE-DEGRADE",
          "SAG-DRIVE",
          "Main-drive or gear-mesh degradation",
          "wear",
          ["lubrication loss", "misalignment", "tooth damage", "overload", "foundation movement"],
          ["torque loss", "abnormal vibration", "tooth damage progression", "loss of mill availability"],
          ["vibration", "motor_current", "thermal", "oil_analysis", "inspection"],
          ["gear_contact_inspection", "alignment_survey", "backlash_check", "oil_sample_confirmation"],
          5,
        ),
      ],
    },
    {
      code: "SAG-LUBE-COOL",
      name: "Lubrication, jacking, filtration, and cooling systems",
      functions: ["deliver lubricant", "lift bearing surfaces during required states", "remove contaminants", "reject heat"],
      telemetryConcepts: ["lubricant_pressure", "jacking_pressure", "lubricant_flow", "lubricant_temperature", "filter_differential_pressure", "lubricant_condition"],
      inspectionZones: ["reservoirs", "pumps", "filters", "coolers", "distribution lines", "spray systems", "sample points"],
      failureModes: [
        draftFailure(
          "SAG-LUBE-LOSS",
          "SAG-LUBE-COOL",
          "Lubrication, jacking, or cooling performance loss",
          "wear",
          ["pump failure", "blocked line", "filter bypass", "cooler fouling", "leakage", "contamination"],
          ["bearing or gear damage", "abnormal heat", "failed start or stop support", "secondary drivetrain failure"],
          ["pressure", "flow", "temperature", "oil_analysis", "inspection"],
          ["lubrication_system_function_test", "oil_sample_confirmation", "cooler_performance_check", "distribution_point_inspection"],
          5,
        ),
      ],
    },
    {
      code: "SAG-FEED-DISCHARGE",
      name: "Feed chute, trommel, discharge, and slurry interfaces",
      functions: ["admit feed", "control discharge", "retain grinding media", "route slurry and oversize"],
      telemetryConcepts: ["feed_rate", "feed_density", "discharge_flow", "trommel_vibration", "chute_blockage", "spillage"],
      inspectionZones: ["feed chute", "feed spout", "discharge grate", "pulp lifters", "trommel", "launders", "seals"],
      failureModes: [
        draftFailure(
          "SAG-FLOW-INTERFACE-DEGRADE",
          "SAG-FEED-DISCHARGE",
          "Feed or discharge blockage, wear, or containment loss",
          "abrasion and blockage",
          ["oversize material", "high wear", "liner damage", "poor flow", "seal deterioration"],
          ["reduced throughput", "spillage", "process instability", "secondary equipment damage"],
          ["fixed_camera", "rgb_visual_inspection", "flow", "vibration", "inspection"],
          ["isolated_internal_inspection", "wear_measurement", "flow_path_inspection", "process_review"],
          4,
        ),
      ],
    },
    {
      code: "SAG-CTRL-PROTECT",
      name: "Instrumentation, controls, interlocks, and protection",
      functions: ["measure operating condition", "control mill sequence", "protect equipment and personnel", "record events"],
      telemetryConcepts: ["mill_speed", "mill_power", "bearing_temperature", "lubrication_status", "vibration_trip_status", "fault_code", "communication_health"],
      inspectionZones: ["sensors", "PLC and remote I/O", "drive controls", "interlocks", "protective devices", "networks"],
      failureModes: [
        draftFailure(
          "SAG-CTRL-PROTECT-FAULT",
          "SAG-CTRL-PROTECT",
          "Control, instrumentation, or protective-function degradation",
          "functional failure",
          ["sensor drift", "wiring damage", "logic fault", "communication loss", "bypassed protection"],
          ["incorrect operation", "missed protection", "nuisance trip", "unsafe or damaging sequence"],
          ["fault_code", "signal_validation", "inspection", "functional_test"],
          ["instrument_calibration_check", "interlock_function_test", "logic_review", "independent_engineering_verification"],
          5,
        ),
      ],
    },
  ],
};
