import {
  flexibleCouplingDna,
  frictionBrakeDna,
  hydraulicCylinderDna,
  industrialAcMotorDna,
  industrialGearboxComponentDna,
  lubricationSystemDna,
  rollingElementBearingDna,
  sheaveDna,
  switchgearDna,
  transformerDna,
  variableFrequencyDriveDna,
  wireRopeDna,
} from "./shared-component-dna-library";
import type { AssetClassTemplate, FailureModeTemplate } from "./types";

const draftFailure = (
  code: string,
  componentCode: string,
  name: string,
  mechanism: string,
  causes: string[],
  effects: string[],
  detectableBy: string[],
  verificationMethods: string[],
  severity: 1 | 2 | 3 | 4 | 5,
): FailureModeTemplate => ({
  code,
  componentCode,
  name,
  mechanism,
  causes,
  effects,
  detectableBy,
  verificationMethods,
  recommendedActions: [],
  severity,
  evidence: [],
  reviewState: "draft",
});

/**
 * Manufacturer-neutral boom-type stockyard stacker-reclaimer.
 *
 * Portal/bridge scraper reclaimers share travel, structure, and electrical
 * concepts; reclaim-mechanism geometry is site-specific. This is one asset
 * class, not a second hierarchy. Boom-conveyor intelligence is referenced
 * through shared component DNA — it does not copy `FP-CONVEYOR-BELT`.
 *
 * Numeric intervals, alarm limits, and retirement criteria require approved
 * OEM or site evidence. Recommend does not authorize work.
 */
export const stackerReclaimerTemplate: AssetClassTemplate = {
  schemaVersion: "0.1.0",
  code: "MIN-STACK-RECLAIM",
  name: "Stacker-reclaimer",
  family: "fixed_material_handling",
  description:
    "Governed component, failure, telemetry, and inspection foundation for boom-type stockyard stacker-reclaimers. Draft manufacturer-neutral content only; limits and intervals require approved evidence.",
  functions: [
    "stack",
    "reclaim",
    "slew",
    "luff",
    "travel",
    "convey_on_boom",
    "control_electrical_power",
    "lubricate",
  ],
  operatingStates: [
    "offline",
    "isolated",
    "idle",
    "stacking",
    "reclaiming",
    "slewing",
    "luffing",
    "travelling",
    "maintenance_test",
  ],
  standards: ["ISO 55000", "ISO 13374", "ISO 23247"],
  reviewState: "draft",
  components: [
    {
      code: "SR-STRUCT",
      name: "Boom, pylon, counterweight, and supporting structure",
      functions: [
        "support boom and reclaiming loads",
        "maintain geometry",
        "transfer slew, luff, and travel reactions",
      ],
      telemetryConcepts: [
        "structural_strain",
        "boom_deflection",
        "cycle_count",
        "counterweight_position",
        "wind_speed",
      ],
      inspectionZones: [
        "boom chords",
        "boom foot",
        "pylon or mast",
        "counterweight structure",
        "portal or undercarriage frames",
        "access walkways",
      ],
      failureModes: [
        draftFailure(
          "SR-STRUCT-FATIGUE",
          "SR-STRUCT",
          "Structural fatigue cracking or distortion",
          "fatigue crack initiation and propagation under cyclic stacking, reclaiming, and wind loads",
          [
            "cyclic loading",
            "stress concentration",
            "corrosion",
            "impact",
            "geometry deviation",
          ],
          [
            "reduced structural capacity",
            "load-path redistribution",
            "restricted boom motion",
          ],
          [
            "drone_rgb",
            "drone_thermal",
            "drone_lidar",
            "strain_monitoring",
            "inspection",
          ],
          [
            "non_destructive_testing",
            "dimensional_survey",
            "structural_engineering_assessment",
          ],
          5,
        ),
      ],
    },
    {
      code: "SR-SLEW",
      name: "Slew bearing and slew drives",
      sharedComponentDnaCodes: [
        industrialAcMotorDna.code,
        industrialGearboxComponentDna.code,
        rollingElementBearingDna.code,
      ],
      functions: [
        "rotate the boom about the slew axis",
        "control slew acceleration and holding",
        "support rotating mass",
      ],
      telemetryConcepts: [
        "slew_position",
        "slew_speed",
        "motor_current",
        "gearcase_temperature",
        "bearing_temperature",
        "bearing_vibration",
      ],
      inspectionZones: [
        "slew bearing",
        "slew motors",
        "slew gearboxes",
        "pinions",
        "slew rack or ring gear",
        "holding brakes",
      ],
      failureModes: [
        draftFailure(
          "SR-SLEW-DEGRADE",
          "SR-SLEW",
          "Slew drive or bearing degradation",
          "wear, lubrication loss, or misalignment increases friction, heat, and backlash",
          [
            "lubrication loss",
            "contamination",
            "uneven loading",
            "misalignment",
            "overload",
          ],
          [
            "abnormal heat",
            "vibration",
            "poor slew control",
            "loss of slew availability",
          ],
          [
            "vibration",
            "thermal",
            "oil_analysis",
            "motor_current",
            "inspection",
          ],
          [
            "gear_contact_inspection",
            "bearing_inspection",
            "oil_sample_confirmation",
            "alignment_survey",
          ],
          5,
        ),
      ],
    },
    {
      code: "SR-LUFF",
      name: "Luffing, hoist, and boom-raise system",
      sharedComponentDnaCodes: [
        wireRopeDna.code,
        sheaveDna.code,
        hydraulicCylinderDna.code,
        industrialAcMotorDna.code,
        frictionBrakeDna.code,
      ],
      functions: [
        "raise and lower the boom",
        "hold commanded boom angle",
        "guide hoist or cylinder load paths",
      ],
      telemetryConcepts: [
        "boom_angle",
        "luff_position",
        "rope_load",
        "motor_current",
        "hydraulic_pressure",
        "brake_status",
      ],
      inspectionZones: [
        "luffing winch or cylinders",
        "hoist ropes",
        "sheaves",
        "equalizers",
        "brakes",
        "boom-raise pins",
      ],
      failureModes: [
        draftFailure(
          "SR-LUFF-DEGRADE",
          "SR-LUFF",
          "Luffing rope, sheave, cylinder, or brake degradation",
          "bending fatigue, abrasion, leakage, or incomplete brake release prevents controlled boom motion",
          [
            "bending cycles",
            "abrasion",
            "corrosion",
            "hydraulic leakage",
            "brake drag",
            "sheave misalignment",
          ],
          [
            "loss of boom-angle control",
            "uncommanded boom motion",
            "secondary structural damage",
          ],
          [
            "drone_rgb",
            "rgb_visual_inspection",
            "position",
            "pressure",
            "motor_current",
            "inspection",
          ],
          [
            "qualified_rope_inspection",
            "sheave_geometry_check",
            "cylinder_or_winch_inspection",
            "brake_function_test",
          ],
          5,
        ),
      ],
    },
    {
      code: "SR-TRAVEL",
      name: "Long-travel drives, wheels, and rail interface",
      sharedComponentDnaCodes: [
        industrialAcMotorDna.code,
        industrialGearboxComponentDna.code,
        rollingElementBearingDna.code,
      ],
      functions: [
        "translate the machine along the stockyard",
        "maintain rail guidance",
        "control travel starts and stops",
      ],
      telemetryConcepts: [
        "travel_position",
        "travel_speed",
        "motor_current",
        "wheel_bearing_temperature",
        "rail_alignment",
        "storm_lock_status",
      ],
      inspectionZones: [
        "travel motors",
        "travel gearboxes",
        "wheels and axles",
        "rails and clips",
        "buffers",
        "storm locks or rail clamps",
      ],
      failureModes: [
        draftFailure(
          "SR-TRAVEL-DEGRADE",
          "SR-TRAVEL",
          "Travel drive, wheel, or rail-interface degradation",
          "wear, misalignment, or lubrication loss increases rolling resistance and tracking error",
          [
            "rail wear or settlement",
            "wheel-flange wear",
            "lubrication loss",
            "overload",
            "obstruction",
          ],
          [
            "restricted travel",
            "derailment risk",
            "abnormal heat",
            "loss of positioning",
          ],
          [
            "drone_rgb",
            "drone_lidar",
            "thermal",
            "motor_current",
            "position_monitoring",
            "inspection",
          ],
          [
            "wheel_and_rail_measurement",
            "drivetrain_inspection",
            "alignment_survey",
            "lock_function_test",
          ],
          5,
        ),
      ],
    },
    {
      code: "SR-BOOM-CONV",
      name: "Boom conveyor and stacking discharge",
      sharedComponentDnaCodes: [
        rollingElementBearingDna.code,
        flexibleCouplingDna.code,
        industrialAcMotorDna.code,
        industrialGearboxComponentDna.code,
        lubricationSystemDna.code,
      ],
      functions: [
        "transport material along the boom",
        "discharge for stacking",
        "receive reclaimed material",
      ],
      telemetryConcepts: [
        "belt_speed",
        "belt_tracking",
        "motor_current",
        "bearing_temperature",
        "load_rate",
        "discharge_state",
      ],
      inspectionZones: [
        "boom belt and splices",
        "pulleys",
        "idlers",
        "drive",
        "discharge chute",
        "skirts",
      ],
      failureModes: [
        draftFailure(
          "SR-BOOM-CONV-DEGRADE",
          "SR-BOOM-CONV",
          "Boom-conveyor belt, idler, or drive degradation",
          "wear, tracking loss, or drivetrain deterioration interrupts stacking or reclaim conveying",
          [
            "mis-tracking",
            "idler seizure",
            "splice deterioration",
            "overload",
            "lubrication loss",
          ],
          [
            "material spillage",
            "belt damage",
            "unplanned stop",
            "reduced stacking or reclaim rate",
          ],
          [
            "drone_rgb",
            "drone_thermal",
            "belt_speed",
            "vibration",
            "inspection",
          ],
          [
            "deenergized_visual_inspection",
            "idler_or_pulley_inspection",
            "drive_alignment_check",
            "splice_assessment",
          ],
          5,
        ),
      ],
    },
    {
      code: "SR-RECLAIM",
      name: "Reclaiming mechanism",
      sharedComponentDnaCodes: [
        industrialAcMotorDna.code,
        industrialGearboxComponentDna.code,
        rollingElementBearingDna.code,
      ],
      functions: [
        "recover material from the stockpile",
        "control reclaim cut geometry",
        "feed the boom conveyor",
      ],
      telemetryConcepts: [
        "reclaim_speed",
        "motor_current",
        "gearbox_temperature",
        "bearing_vibration",
        "reclaim_rate",
        "cut_depth",
      ],
      inspectionZones: [
        "bucket wheel or scraper head",
        "buckets or blades",
        "cell or chain structure",
        "reclaim drive",
        "chute interface",
      ],
      failureModes: [
        draftFailure(
          "SR-RECLAIM-DEGRADE",
          "SR-RECLAIM",
          "Reclaiming-mechanism wear or drive degradation",
          "abrasion, impact, or drivetrain distress changes cut geometry and reduces reclaim availability",
          [
            "abrasive feed",
            "impact",
            "lubrication loss",
            "overload",
            "foreign object",
          ],
          [
            "reduced reclaim rate",
            "abnormal vibration or heat",
            "material hang-up",
            "secondary chute or belt damage",
          ],
          [
            "drone_rgb",
            "thermal",
            "vibration",
            "motor_current",
            "inspection",
          ],
          [
            "wear_measurement",
            "drivetrain_inspection",
            "oil_sample_confirmation",
            "engineer_visual",
          ],
          4,
        ),
      ],
    },
    {
      code: "SR-ELEC-CTRL",
      name: "Electrical power, drives, controls, and protection",
      sharedComponentDnaCodes: [
        switchgearDna.code,
        variableFrequencyDriveDna.code,
        transformerDna.code,
      ],
      functions: [
        "distribute electrical power",
        "control slew, luff, travel, and conveying motions",
        "protect personnel and equipment",
        "record operating events",
      ],
      telemetryConcepts: [
        "voltage",
        "current",
        "cabinet_temperature",
        "fault_code",
        "interlock_state",
        "communication_health",
        "anti_collision_state",
      ],
      inspectionZones: [
        "incoming power",
        "transformers",
        "switchgear",
        "drive cabinets",
        "cable reels or festoon",
        "protective devices",
        "anti-collision sensors",
      ],
      failureModes: [
        draftFailure(
          "SR-ELEC-DEGRADE",
          "SR-ELEC-CTRL",
          "Electrical connection, drive, interlock, or protection fault",
          "loose connections, cooling loss, sensor faults, or configuration errors compromise motion control or protective response",
          [
            "loose connections",
            "contamination",
            "cooling loss",
            "sensor damage",
            "configuration error",
          ],
          [
            "thermal damage",
            "nuisance trip",
            "failure to trip",
            "loss of motion or protection",
          ],
          [
            "thermal",
            "fault_code",
            "current_imbalance",
            "proof_test",
            "inspection",
          ],
          [
            "deenergized_electrical_inspection",
            "approved_proof_test",
            "insulation_test",
            "configuration_review",
          ],
          5,
        ),
      ],
    },
    {
      code: "SR-LUBE",
      name: "Lubrication and support systems",
      sharedComponentDnaCodes: [lubricationSystemDna.code],
      functions: [
        "deliver lubricant",
        "control contamination",
        "support slew, travel, reclaim, and conveyor bearings",
      ],
      telemetryConcepts: [
        "lubricant_pressure",
        "lubricant_flow",
        "reservoir_level",
        "filter_differential_pressure",
        "lubricant_condition",
      ],
      inspectionZones: [
        "reservoirs",
        "pumps",
        "distribution blocks",
        "lines",
        "slew-bearing lubrication points",
        "sample points",
      ],
      failureModes: [
        draftFailure(
          "SR-LUBE-LOSS",
          "SR-LUBE",
          "Lubrication delivery loss or contamination",
          "blocked lines, failed pumps, leakage, or wrong lubricant starve bearings and open gears",
          [
            "pump failure",
            "blocked line",
            "leakage",
            "empty reservoir",
            "wrong lubricant",
          ],
          [
            "accelerated bearing and gear wear",
            "heat generation",
            "secondary drive failure",
          ],
          ["pressure", "flow", "temperature", "oil_analysis", "inspection"],
          [
            "lubrication_system_function_test",
            "oil_sample_confirmation",
            "distribution_point_inspection",
          ],
          5,
        ),
      ],
    },
  ],
};
