import type { AssetClassTemplate, FailureModeTemplate } from "./types";

const draftFailure = (
  code: string,
  componentCode: string,
  name: string,
  mechanism: string,
  causes: string[],
  effects: string[],
  detectableBy: string[],
  verificationMethods: string[],
  severity: 1 | 2 | 3 | 4 | 5,
): FailureModeTemplate => ({
  code,
  componentCode,
  name,
  mechanism,
  causes,
  effects,
  detectableBy,
  verificationMethods,
  recommendedActions: [],
  severity,
  evidence: [],
  reviewState: "draft",
});

/** Manufacturer-neutral thickener template. Approved OEM and site evidence is required for limits, setpoints, intervals, pressures, and acceptance criteria. */
export const thickenerTemplate: AssetClassTemplate = {
  schemaVersion: "0.1.0",
  code: "PROC-THICKENER",
  name: "Mineral processing thickener",
  family: "fixed_material_processing",
  description:
    "Governed engineering foundation for manufacturer-neutral mineral-processing thickeners used for slurry clarification, solids settling, and underflow concentration.",
  functions: [
    "receive_and_distribute_slurry_feed",
    "promote_solids_settling_and_compaction",
    "clarify_overflow_liquor",
    "collect_and_move_settled_solids",
    "discharge_underflow_slurry",
    "support_rake_drive_and_lifting_systems",
    "protect_equipment_and_process_interfaces",
  ],
  operatingStates: [
    "offline",
    "starting",
    "running_normal",
    "running_high_load",
    "rake_lift",
    "stopping",
    "maintenance_test",
  ],
  standards: ["ISO 55000", "ISO 13374", "ISO 23247"],
  reviewState: "draft",
  components: [
    {
      code: "THK-STRUCTURE",
      name: "Tank, bridge, center column, and structural supports",
      functions: [
        "contain slurry and clarified liquor",
        "support bridge and drive loads",
        "maintain tank geometry",
        "provide access and structural stability",
      ],
      telemetryConcepts: [
        "structural_vibration",
        "bridge_deflection",
        "tank_leakage",
        "corrosion_condition",
      ],
      inspectionZones: [
        "tank shell",
        "floor and cone interfaces",
        "bridge",
        "center column",
        "support steel",
        "walkways",
        "foundation interfaces",
      ],
      failureModes: [
        draftFailure(
          "THK-STRUCTURE-DEGRADE",
          "THK-STRUCTURE",
          "Tank, bridge, center-column, or support degradation",
          "corrosion, fatigue, settlement, or mechanical damage",
          [
            "corrosive service",
            "cyclic loading",
            "settlement",
            "impact damage",
            "coating degradation",
          ],
          [
            "loss of containment",
            "misalignment",
            "unsafe access",
            "reduced structural capacity",
            "unplanned outage",
          ],
          [
            "inspection",
            "drone_rgb",
            "drone_lidar",
            "leak_detection",
            "structural_vibration",
          ],
          [
            "structural_engineering_inspection",
            "non_destructive_testing",
            "alignment_survey",
            "coating_and_corrosion_assessment",
          ],
          5,
        ),
      ],
    },
    {
      code: "THK-RAKE-LIFT",
      name: "Rake arms, blades, trusses, and lifting mechanism",
      functions: [
        "collect settled solids",
        "move solids toward the underflow cone",
        "maintain rake geometry",
        "raise rake assembly where fitted",
      ],
      telemetryConcepts: [
        "rake_position",
        "rake_lift_status",
        "rake_travel",
        "rake_vibration",
        "bed_level",
      ],
      inspectionZones: [
        "rake arms",
        "rake blades",
        "rake trusses",
        "lift mechanism",
        "turntable interface",
        "submerged fasteners",
      ],
      failureModes: [
        draftFailure(
          "THK-RAKE-LIFT-DEGRADE",
          "THK-RAKE-LIFT",
          "Rake, blade, truss, or lifting-mechanism degradation",
          "wear, deformation, misalignment, or overload-related distress",
          [
            "abrasive solids",
            "settled bed resistance",
            "misalignment",
            "foreign material",
            "corrosion",
            "fastener loosening",
          ],
          [
            "reduced solids transport",
            "rake interference",
            "drive overload",
            "underflow instability",
            "unplanned shutdown",
          ],
          [
            "rake_position",
            "rake_vibration",
            "torque",
            "bed_level",
            "inspection",
          ],
          [
            "isolated_internal_inspection",
            "rake_alignment_check",
            "mechanical_clearance_check",
            "qualified_engineering_review",
          ],
          5,
        ),
      ],
    },
    {
      code: "THK-DRIVE",
      name: "Drive, gearbox, bearings, and torque transmission",
      functions: [
        "generate rake rotation",
        "transmit torque to the rake mechanism",
        "support rotating loads",
        "protect the drive train from abnormal resistance",
      ],
      telemetryConcepts: [
        "drive_current",
        "drive_power",
        "torque",
        "gearbox_vibration",
        "gearbox_temperature",
        "bearing_temperature",
        "drive_fault_code",
      ],
      inspectionZones: [
        "drive motor",
        "gearbox",
        "coupling",
        "bearings",
        "torque transmission path",
        "guards",
        "mounting interfaces",
      ],
      failureModes: [
        draftFailure(
          "THK-DRIVE-DEGRADE",
          "THK-DRIVE",
          "Drive, gearbox, bearing, or torque-transmission degradation",
          "wear, misalignment, lubrication-related distress, or overload-related damage",
          [
            "lubrication loss",
            "misalignment",
            "excessive settled-bed resistance",
            "tooth damage",
            "bearing wear",
            "foundation movement",
          ],
          [
            "loss of rake motion",
            "abnormal heat",
            "vibration",
            "drive trip",
            "secondary rake damage",
          ],
          [
            "drive_current",
            "torque",
            "vibration",
            "temperature",
            "oil_analysis",
            "fault_code",
            "inspection",
          ],
          [
            "drive_alignment_survey",
            "gear_contact_inspection",
            "oil_sample_confirmation",
            "bearing_inspection",
            "qualified_drive_review",
          ],
          5,
        ),
      ],
    },
    {
      code: "THK-FEEDWELL",
      name: "Feedwell and feed distribution",
      functions: [
        "receive incoming slurry",
        "dissipate feed energy",
        "distribute feed into the settling zone",
        "support flocculant and dilution interfaces where fitted",
      ],
      telemetryConcepts: [
        "feed_rate",
        "feed_density",
        "feedwell_level",
        "feed_distribution_condition",
        "flocculant_flow_status",
      ],
      inspectionZones: [
        "feed pipe",
        "feedwell shell",
        "baffles",
        "dilution ports",
        "flocculant addition points",
        "wear liners",
      ],
      failureModes: [
        draftFailure(
          "THK-FEEDWELL-MALDISTRIBUTION",
          "THK-FEEDWELL",
          "Feedwell damage, blockage, or maldistribution",
          "abrasion, blockage, flow disturbance, or structural damage",
          [
            "abrasive slurry",
            "coarse material",
            "blocked feed path",
            "baffle damage",
            "poor mixing",
            "liner degradation",
          ],
          [
            "short circuiting",
            "poor settling",
            "overflow quality change",
            "rake load increase",
            "process instability",
          ],
          [
            "feed_rate",
            "feed_density",
            "fixed_camera",
            "inspection",
            "process_trend",
          ],
          [
            "feedwell_internal_inspection",
            "wear_measurement",
            "flow_path_inspection",
            "process_review",
          ],
          4,
        ),
      ],
    },
    {
      code: "THK-OVERFLOW",
      name: "Overflow launders and clarification interface",
      functions: [
        "collect clarified liquor",
        "maintain overflow routing",
        "limit solids carryover through governed operation",
        "contain and route overflow to downstream process",
      ],
      telemetryConcepts: [
        "overflow_flow",
        "overflow_turbidity",
        "overflow_solids_indication",
        "launder_blockage",
        "clarification_condition",
      ],
      inspectionZones: [
        "overflow launders",
        "weirs",
        "collection channels",
        "launder outlets",
        "seals",
        "clarification zone",
      ],
      failureModes: [
        draftFailure(
          "THK-OVERFLOW-DEGRADE",
          "THK-OVERFLOW",
          "Overflow blockage, containment loss, or clarification degradation",
          "blockage, wear, corrosion, solids carryover, or flow maldistribution",
          [
            "scale or solids buildup",
            "corrosion",
            "weir damage",
            "poor settling",
            "launder wear",
            "seal deterioration",
          ],
          [
            "overflow spill",
            "solids carryover",
            "downstream process upset",
            "environmental or housekeeping exposure",
          ],
          [
            "overflow_flow",
            "overflow_turbidity",
            "fixed_camera",
            "inspection",
            "spill_detection",
          ],
          [
            "launder_inspection",
            "weir_condition_check",
            "flow_path_inspection",
            "process_sample_review",
          ],
          4,
        ),
      ],
    },
    {
      code: "THK-UNDERFLOW",
      name: "Underflow cone, discharge, and pumping interface",
      functions: [
        "collect compacted solids",
        "route underflow slurry",
        "interface with discharge valves and pumps",
        "preserve containment at the discharge interface",
      ],
      telemetryConcepts: [
        "underflow_flow",
        "underflow_density",
        "discharge_blockage",
        "pump_interface_status",
        "spillage",
      ],
      inspectionZones: [
        "underflow cone",
        "discharge nozzle",
        "underflow valves",
        "pump suction interface",
        "discharge piping",
        "containment seals",
      ],
      failureModes: [
        draftFailure(
          "THK-UNDERFLOW-DEGRADE",
          "THK-UNDERFLOW",
          "Underflow blockage, wear, containment loss, or pumping-interface degradation",
          "abrasion, plugging, leakage, or solids-handling instability",
          [
            "high solids loading",
            "coarse material",
            "abrasive slurry",
            "valve restriction",
            "pump suction disturbance",
            "seal deterioration",
          ],
          [
            "reduced underflow withdrawal",
            "rake load increase",
            "spillage",
            "pump instability",
            "process upset",
          ],
          [
            "underflow_flow",
            "underflow_density",
            "fixed_camera",
            "inspection",
            "spillage",
          ],
          [
            "underflow_path_inspection",
            "wear_measurement",
            "valve_function_check",
            "pump_interface_review",
          ],
          4,
        ),
      ],
    },
    {
      code: "THK-LUBE-HYD",
      name: "Lubrication, hydraulic lifting, and support systems",
      functions: [
        "deliver lubricant",
        "support lifting mechanism operation where fitted",
        "exclude contamination",
        "support controlled testing and maintenance states",
      ],
      telemetryConcepts: [
        "lubricant_flow",
        "lubricant_temperature",
        "lubricant_condition",
        "filter_differential_condition",
        "hydraulic_lift_status",
        "reservoir_level",
      ],
      inspectionZones: [
        "lubrication reservoir",
        "lubrication pumps",
        "filters",
        "distribution lines",
        "hydraulic power unit if fitted",
        "lift cylinders or actuators if fitted",
        "sample points",
      ],
      failureModes: [
        draftFailure(
          "THK-LUBE-HYD-LOSS",
          "THK-LUBE-HYD",
          "Lubrication, hydraulic lifting, or support-system performance loss",
          "functional degradation from loss of lubricant delivery, contamination control, or lift support",
          [
            "pump failure",
            "blocked line",
            "filter bypass",
            "leakage",
            "contamination",
            "actuator fault",
          ],
          [
            "drive or bearing damage",
            "failed rake lift support",
            "abnormal heat",
            "maintenance-test failure",
            "secondary mechanical damage",
          ],
          [
            "flow",
            "temperature",
            "oil_analysis",
            "hydraulic_lift_status",
            "inspection",
          ],
          [
            "lubrication_system_function_test",
            "oil_sample_confirmation",
            "distribution_point_inspection",
            "lift_function_test",
          ],
          5,
        ),
      ],
    },
    {
      code: "THK-CTRL-PROTECT",
      name: "Instrumentation, controls, interlocks, and protection",
      functions: [
        "measure thickener operating condition",
        "control rake and discharge sequences",
        "protect equipment and personnel",
        "record events and protective actions",
      ],
      telemetryConcepts: [
        "torque",
        "bed_level",
        "rake_position",
        "drive_status",
        "underflow_density",
        "overflow_turbidity",
        "interlock_status",
        "fault_code",
        "communication_health",
      ],
      inspectionZones: [
        "torque measurement",
        "bed-level instruments",
        "rake position sensors",
        "drive controls",
        "PLC and remote I/O",
        "interlocks",
        "protective devices",
        "networks",
      ],
      failureModes: [
        draftFailure(
          "THK-CTRL-PROTECT-FAULT",
          "THK-CTRL-PROTECT",
          "Instrumentation, control, interlock, or protective-function degradation",
          "functional failure",
          [
            "sensor drift",
            "wiring damage",
            "logic fault",
            "communication loss",
            "bypassed protection",
            "instrument fouling",
          ],
          [
            "incorrect operation",
            "missed protection",
            "nuisance trip",
            "unsafe or damaging sequence",
            "poor process visibility",
          ],
          [
            "fault_code",
            "signal_validation",
            "inspection",
            "functional_test",
            "communication_health",
          ],
          [
            "instrument_calibration_check",
            "interlock_function_test",
            "logic_review",
            "independent_engineering_verification",
          ],
          5,
        ),
      ],
    },
  ],
};
