import type { InspectionZoneContract } from "./inspection-contracts";

const baseSafety: InspectionZoneContract["safety"] = {
  isolationState: "site_defined",
  siteApprovalRequired: true,
  exclusionZoneRequired: true,
  spotterRequired: true,
  weatherLimitsSource: "mission_specific_assessment",
  prohibitedConditions: [
    "uncontrolled vehicle movement",
    "personnel within the approved exclusion area",
    "unapproved energized access",
    "conditions outside aircraft, site, or mission limits",
  ],
};

export const ultraClassHaulTruckInspectionZones: InspectionZoneContract[] = [
  {
    schemaVersion: "0.1.0",
    code: "HAUL-TRUCK-INSPECT-STRUCTURE",
    assetClassCode: "MIN-HAUL-TRUCK",
    componentCode: "HT-STRUCT",
    name: "Frame and load-body structural inspection",
    purpose: "Create repeatable evidence for visible cracking, deformation, impact damage, and geometry change.",
    targetAreas: ["main frame rails", "cross members", "dump body", "hinge points", "ROPS/FOPS structure"],
    captures: [
      {
        modality: "drone_rgb",
        objective: "Capture repeatable high-resolution structural imagery.",
        required: true,
        repeatabilityKey: "haul-truck-structure-rgb",
        acceptanceCriteria: ["all approved target areas visible", "image scale and orientation recorded", "obstructions documented"],
      },
      {
        modality: "drone_lidar",
        objective: "Capture geometry suitable for approved comparative deformation assessment.",
        required: false,
        repeatabilityKey: "haul-truck-structure-lidar",
        acceptanceCriteria: ["approved reference geometry included", "coverage gaps documented"],
      },
    ],
    safety: baseSafety,
    evidence: [],
    reviewState: "draft",
  },
  {
    schemaVersion: "0.1.0",
    code: "HAUL-TRUCK-INSPECT-POWER",
    assetClassCode: "MIN-HAUL-TRUCK",
    componentCode: "HT-POWER",
    name: "Prime mover and power-conversion inspection",
    purpose: "Record visible condition and comparative thermal evidence around the engine, power conversion, intake, exhaust, and mounts.",
    targetAreas: ["engine", "alternator or transmission", "intake", "exhaust", "mounts"],
    captures: [
      {
        modality: "drone_rgb",
        objective: "Document leakage, loose or displaced parts, mount condition, and external damage.",
        required: true,
        repeatabilityKey: "haul-truck-power-rgb",
        acceptanceCriteria: ["target areas visible", "leaks and obstructions documented", "operating state recorded"],
      },
      {
        modality: "drone_thermal",
        objective: "Capture comparative temperature patterns without applying universal alarm thresholds.",
        required: false,
        repeatabilityKey: "haul-truck-power-thermal",
        acceptanceCriteria: ["operating context recorded", "emissivity assumptions documented", "comparison basis identified"],
      },
    ],
    safety: baseSafety,
    evidence: [],
    reviewState: "draft",
  },
  {
    schemaVersion: "0.1.0",
    code: "HAUL-TRUCK-INSPECT-DRIVE-BRAKE",
    assetClassCode: "MIN-HAUL-TRUCK",
    componentCode: "HT-DRIVE",
    name: "Propulsion, final-drive, and wheel-end inspection",
    purpose: "Capture external condition and comparative thermal evidence for drive and wheel-end degradation.",
    targetAreas: ["wheel motors or transmission", "final drives", "drive shafts", "axles", "wheel ends"],
    captures: [
      {
        modality: "drone_rgb",
        objective: "Document leakage, fastener condition, impact damage, and visible movement indicators.",
        required: true,
        repeatabilityKey: "haul-truck-drive-rgb",
        acceptanceCriteria: ["all approved wheel ends included", "left-right identity preserved", "obstructions documented"],
      },
      {
        modality: "drone_thermal",
        objective: "Capture side-to-side and historical thermal comparison evidence.",
        required: true,
        repeatabilityKey: "haul-truck-drive-thermal",
        acceptanceCriteria: ["comparable operating context recorded", "left-right wheel identity preserved", "ambient conditions recorded"],
      },
    ],
    safety: baseSafety,
    evidence: [],
    reviewState: "draft",
  },
  {
    schemaVersion: "0.1.0",
    code: "HAUL-TRUCK-INSPECT-BRAKE",
    assetClassCode: "MIN-HAUL-TRUCK",
    componentCode: "HT-BRAKE",
    name: "Braking and retarding inspection",
    purpose: "Collect evidence for leakage, incomplete release, uneven heating, and visible brake-system damage.",
    targetAreas: ["service brakes", "parking brake", "retarding equipment", "brake lines", "accumulators"],
    captures: [
      {
        modality: "drone_rgb",
        objective: "Document external brake-system condition and leakage evidence.",
        required: true,
        repeatabilityKey: "haul-truck-brake-rgb",
        acceptanceCriteria: ["approved brake targets visible", "fluid evidence documented", "vehicle state recorded"],
      },
      {
        modality: "drone_thermal",
        objective: "Capture comparative brake and wheel temperature patterns.",
        required: true,
        repeatabilityKey: "haul-truck-brake-thermal",
        acceptanceCriteria: ["operating and braking context recorded", "wheel identity preserved", "no universal threshold inferred"],
      },
    ],
    safety: baseSafety,
    evidence: [],
    reviewState: "draft",
  },
  {
    schemaVersion: "0.1.0",
    code: "HAUL-TRUCK-INSPECT-STEER-SUSP",
    assetClassCode: "MIN-HAUL-TRUCK",
    componentCode: "HT-STEER-SUSP",
    name: "Steering and suspension inspection",
    purpose: "Create repeatable evidence for leakage, strut condition, linkage damage, and abnormal geometry.",
    targetAreas: ["steering cylinders", "linkages", "suspension struts", "pins", "mounts"],
    captures: [
      {
        modality: "drone_rgb",
        objective: "Document leakage, damage, pin movement indicators, and ride-height asymmetry.",
        required: true,
        repeatabilityKey: "haul-truck-steer-susp-rgb",
        acceptanceCriteria: ["left-right identity preserved", "target joints visible", "load state documented"],
      },
      {
        modality: "drone_lidar",
        objective: "Capture geometry for approved comparative alignment and ride-height assessment.",
        required: false,
        repeatabilityKey: "haul-truck-steer-susp-lidar",
        acceptanceCriteria: ["approved reference points included", "vehicle load and ground condition recorded"],
      },
    ],
    safety: baseSafety,
    evidence: [],
    reviewState: "draft",
  },
  {
    schemaVersion: "0.1.0",
    code: "HAUL-TRUCK-INSPECT-ELECTRICAL",
    assetClassCode: "MIN-HAUL-TRUCK",
    componentCode: "HT-ELEC-CTRL",
    name: "External electrical and controls inspection",
    purpose: "Capture external cable, termination, cabinet, sensor, and ventilation condition without opening energized enclosures.",
    targetAreas: ["external cabinets", "traction cables", "accessible terminations", "sensors", "ventilation paths"],
    captures: [
      {
        modality: "drone_rgb",
        objective: "Document cable damage, contamination, displaced covers, and ventilation restriction.",
        required: true,
        repeatabilityKey: "haul-truck-electrical-rgb",
        acceptanceCriteria: ["only approved external targets captured", "enclosure state documented", "no energized access performed"],
      },
      {
        modality: "drone_thermal",
        objective: "Capture approved external comparative thermal patterns.",
        required: false,
        repeatabilityKey: "haul-truck-electrical-thermal",
        acceptanceCriteria: ["load context recorded", "enclosures remain closed unless separately authorized", "comparison basis documented"],
      },
    ],
    safety: baseSafety,
    evidence: [],
    reviewState: "draft",
  },
];

export function getUltraClassHaulTruckInspectionZone(code: string): InspectionZoneContract | undefined {
  return ultraClassHaulTruckInspectionZones.find((zone) => zone.code === code);
}
