import type { AssetClassTemplate, FailureModeTemplate } from "./types";

const draftFailure = (
  code: string,
  componentCode: string,
  name: string,
  mechanism: string,
  causes: string[],
  effects: string[],
  detectableBy: string[],
  verificationMethods: string[],
  severity: 1 | 2 | 3 | 4 | 5,
): FailureModeTemplate => ({
  code,
  componentCode,
  name,
  mechanism,
  causes,
  effects,
  detectableBy,
  verificationMethods,
  recommendedActions: [],
  severity,
  evidence: [],
  reviewState: "draft",
});

/**
 * Manufacturer-neutral engineering template for ultra-class mining haul trucks.
 * Numeric limits and maintenance intervals are intentionally excluded until an
 * approved OEM, customer, or site source is attached.
 */
export const ultraClassHaulTruckTemplate: AssetClassTemplate = {
  schemaVersion: "0.2.0",
  code: "MIN-HAUL-TRUCK",
  name: "Ultra-class haul truck",
  family: "mobile_mining_haulage",
  description:
    "Reusable functional, component, failure and observation template for ultra-class electric or mechanical-drive mining haul trucks.",
  functions: ["load", "haul", "dump", "retard", "brake", "steer", "propel", "support_payload", "cool"],
  operatingStates: [
    "offline",
    "idle",
    "loading",
    "hauling_loaded",
    "dumping",
    "returning_empty",
    "spotting",
    "retarding",
    "maintenance_test",
  ],
  standards: ["ISO 55000", "ISO 13374", "ISO 23247"],
  reviewState: "draft",
  components: [
    {
      code: "HT-STRUCT",
      name: "Frame and load-carrying structure",
      functions: ["support payload", "transmit propulsion and braking loads", "maintain chassis geometry"],
      telemetryConcepts: ["payload", "frame_strain", "cycle_count", "road_shock", "body_position"],
      inspectionZones: ["main frame rails", "cross members", "dump body", "hinge points", "ROPS/FOPS structure"],
      failureModes: [
        draftFailure(
          "HT-STRUCT-CRACK",
          "HT-STRUCT",
          "Structural fatigue crack",
          "cyclic stress concentration causing crack initiation and propagation",
          ["repeated high-energy loading", "weld discontinuity", "impact", "corrosion-assisted fatigue"],
          ["loss of structural capacity", "geometry change", "secondary component damage"],
          ["drone_rgb", "drone_thermal", "drone_lidar", "inspection", "strain_trend"],
          ["magnetic_particle", "phased_array_ultrasonic", "dimensional_survey", "structural_engineering_assessment"],
          5,
        ),
        draftFailure(
          "HT-STRUCT-DEFORM",
          "HT-STRUCT",
          "Permanent structural deformation",
          "overload or impact exceeding local structural capacity",
          ["overload", "collision", "uneven load distribution"],
          ["misalignment", "reduced fatigue life", "interference with adjacent systems"],
          ["drone_lidar", "photogrammetry", "inspection", "payload_history"],
          ["dimensional_survey", "structural_engineering_assessment"],
          4,
        ),
      ],
    },
    {
      code: "HT-POWER",
      name: "Prime mover and power conversion",
      functions: ["generate propulsion power", "support auxiliary loads", "reject heat"],
      telemetryConcepts: ["engine_speed", "fuel_rate", "power_output", "exhaust_temperature", "coolant_temperature", "oil_pressure"],
      inspectionZones: ["engine", "alternator or transmission", "intake", "exhaust", "mounts"],
      failureModes: [
        draftFailure(
          "HT-POWER-OVERHEAT",
          "HT-POWER",
          "Abnormal power-system heating",
          "heat generation exceeds cooling or lubrication capacity",
          ["cooling restriction", "overload", "lubrication loss", "combustion or electrical imbalance"],
          ["derate", "accelerated wear", "loss of propulsion"],
          ["temperature", "drone_thermal", "fault_code", "power_balance"],
          ["cooling_system_test", "oil_analysis", "electrical_test", "engine_performance_test"],
          4,
        ),
        draftFailure(
          "HT-POWER-MOUNT-DAMAGE",
          "HT-POWER",
          "Power-system mount deterioration",
          "mount fatigue, looseness or elastomer degradation permits excess movement",
          ["road shock", "fastener loosening", "material ageing", "misalignment"],
          ["secondary vibration", "hose or cable damage", "driveline misalignment"],
          ["drone_rgb", "inspection", "vibration", "motion_tracking"],
          ["mount_load_test", "fastener_inspection", "alignment_check"],
          3,
        ),
      ],
    },
    {
      code: "HT-DRIVE",
      name: "Propulsion and final drive",
      functions: ["convert power to wheel torque", "control traction", "support retarding where applicable"],
      telemetryConcepts: ["wheel_speed", "drive_current", "drive_pressure", "gearcase_temperature", "bearing_temperature", "slip"],
      inspectionZones: ["wheel motors or transmission", "final drives", "drive shafts", "axles", "traction cables"],
      failureModes: [
        draftFailure(
          "HT-DRIVE-BEARING-DEGRADE",
          "HT-DRIVE",
          "Drive bearing degradation",
          "surface distress, lubrication failure or contamination increases friction and clearance",
          ["contamination", "lubrication loss", "misalignment", "overload"],
          ["abnormal heat", "vibration", "gear damage", "loss of propulsion"],
          ["vibration", "oil_analysis", "drone_thermal", "temperature", "current_signature"],
          ["bearing_inspection", "oil_sample_confirmation", "alignment_check"],
          5,
        ),
      ],
    },
    {
      code: "HT-BRAKE",
      name: "Service braking and retarding",
      functions: ["decelerate vehicle", "hold vehicle stationary", "control downhill speed"],
      telemetryConcepts: ["brake_pressure", "retard_command", "wheel_temperature", "brake_temperature", "deceleration", "parking_brake_state"],
      inspectionZones: ["service brakes", "parking brake", "retarding equipment", "brake lines", "accumulators"],
      failureModes: [
        draftFailure(
          "HT-BRAKE-DRAG",
          "HT-BRAKE",
          "Brake drag or incomplete release",
          "residual braking force generates heat and rolling resistance",
          ["release fault", "mechanical binding", "contamination", "control fault"],
          ["thermal damage", "fuel or energy loss", "reduced braking reserve"],
          ["drone_thermal", "wheel_temperature", "pressure", "cycle_energy"],
          ["brake_release_test", "pressure_decay_test", "qualified_brake_inspection"],
          5,
        ),
        draftFailure(
          "HT-BRAKE-PRESSURE-LOSS",
          "HT-BRAKE",
          "Brake pressure loss",
          "fluid or pneumatic energy is not retained or delivered as commanded",
          ["leak", "accumulator fault", "pump fault", "valve fault"],
          ["increased stopping distance", "loss of braking function", "automatic protective response"],
          ["pressure", "fault_code", "inspection", "leak_detection"],
          ["pressure_hold_test", "leak_test", "functional_brake_test"],
          5,
        ),
      ],
    },
    {
      code: "HT-STEER-SUSP",
      name: "Steering and suspension",
      functions: ["control direction", "support vehicle mass", "attenuate road inputs", "maintain tyre contact"],
      telemetryConcepts: ["steering_pressure", "steering_angle", "suspension_pressure", "strut_temperature", "ride_height", "road_shock"],
      inspectionZones: ["steering cylinders", "linkages", "suspension struts", "pins", "mounts"],
      failureModes: [
        draftFailure(
          "HT-STEER-SUSP-LEAK",
          "HT-STEER-SUSP",
          "Hydraulic or pneumatic leakage",
          "seal, hose, fitting or structural damage permits working fluid escape",
          ["seal wear", "hose damage", "contamination", "impact", "loose fitting"],
          ["loss of control authority", "ride-height change", "environmental release", "component overheating"],
          ["drone_rgb", "inspection", "pressure", "fluid_level", "thermal"],
          ["leak_source_inspection", "pressure_hold_test", "fluid_sample"],
          4,
        ),
      ],
    },
    {
      code: "HT-ELEC-CTRL",
      name: "Electrical power, controls and protection",
      functions: ["distribute electrical power", "control vehicle systems", "protect personnel and equipment", "record faults"],
      telemetryConcepts: ["voltage", "current", "insulation_status", "cabinet_temperature", "fault_code", "communication_health"],
      inspectionZones: ["electrical cabinets", "traction cables", "terminations", "sensors", "control networks"],
      failureModes: [
        draftFailure(
          "HT-ELEC-HOT-CONNECTION",
          "HT-ELEC-CTRL",
          "High-resistance electrical connection",
          "loose, contaminated, corroded or damaged connection produces localized heating",
          ["fastener loosening", "contamination", "corrosion", "conductor damage"],
          ["voltage drop", "thermal damage", "arc fault", "loss of function"],
          ["drone_thermal", "thermal", "current_imbalance", "fault_code"],
          ["deenergized_torque_check", "insulation_test", "electrical_inspection"],
          5,
        ),
      ],
    },
  ],
};
