import type { SyncContextOperatingPicture } from "../../lib/sync-context/operating-picture";
/** Synthetic UI unit fixture. Never imported by runtime/demo/production code. */
export function contextOperatingFixture(
  siteId: string | null = null,
): SyncContextOperatingPicture {
  const source = {
    id: "source-a",
    organizationId: "org-a",
    key: "synthetic-gis",
    name: "Synthetic customer GIS",
    class: "customer_operational" as const,
    authority: "tenant_authorized" as const,
    purpose: "Synthetic governed UI fixture only.",
    rightsState: "customer_authorized" as const,
    state: "connected" as const,
    checkedAt: "2026-10-10T05:00:00Z",
    observedAt: "2026-10-10T04:59:00Z",
    detail: null,
    displayAsLive: false,
  };
  return {
    organizationId: "org-a",
    generatedAt: "2026-10-10T05:01:00Z",
    operationalAuthority: false,
    scope: { siteId, objectLimit: 250, eventLimit: 250 },
    sources: [source],
    issues: [],
    layers: [
      {
        id: "assets_sites",
        label: "Assets and sites",
        renderMode: "object",
        authorized: true,
        sourceDependencies: [source.id],
        healthStates: [source.state],
        availability: "available",
        recordCount: 1,
        candidateCount: 1,
        eligibleCount: 1,
        empty: false,
        degraded: false,
        issues: [],
      },
    ],
    objects: [
      {
        id: "feature-a",
        organizationId: "org-a",
        layerId: "assets_sites",
        kind: "asset",
        name: "Synthetic Pump A",
        geometryType: "Point",
        geometry: { type: "Point", coordinates: [-111.38, 56.73] },
        coordinate: {
          referenceSystem: "EPSG:4326",
          axisOrder: "longitude_latitude",
          basis: "Synthetic explicitly declared WGS84 coordinates.",
          horizontalAccuracyM: null,
        },
        sourceReference: "Synthetic GIS reference, not a customer survey",
        source: {
          id: source.id,
          key: source.key,
          class: source.class,
          authority: source.authority,
          healthState: source.state,
        },
        observedAt: "2026-10-10T04:59:00Z",
        validUntil: null,
        validityKind: "permanent",
        freshness: "current",
        dataQuality: "verified",
        evidenceIds: ["evidence-a"],
        missingEvidence: ["Field survey accuracy not supplied"],
        evidenceState: "verified",
        authority: { operational: false, label: "Verified context evidence" },
        subjects: [
          { type: "asset", id: "ee020000-0000-4000-8000-000000000111" },
          { type: "decision", id: "ee020000-0000-4000-8000-000000000222" },
        ],
        engineeringClaims: [],
        display: { demoOnly: false, live: false, degraded: false },
      },
    ],
    events: [],
    coverage: {
      objects: {
        eligible: 1,
        returned: 1,
        truncated: false,
        draftExcluded: 0,
        expiredExcluded: 0,
        unlinkedExcluded: 0,
        coordinateContractMissing: 0,
        healthBlocked: 0,
        rightsBlocked: 0,
        evidenceBlocked: 0,
        sourceMissing: 0,
        timeBlocked: 0,
        payloadBlocked: 0,
        scopeConflict: 0,
      },
      events: { eligible: 0, returned: 0, truncated: false },
    },
  };
}
